### ISSUE TITLE
Confirmation on task close (do not ask).

### ISSUE THREAD

**Issue by aaron832** [kanboard/kanboard#1019]
I think the confirmation on task close window deserves a (do not ask again).  If someone chooses this option and then accidentally closes the task, they can always re-open it.  Otherwise, its really tedious when closing out multiple tasks.

**Comment by jgbillings** [comment]
Just wanted to note, I too am finding it tedious to close tasks.  Was looking for a keyboard shortcut or a way as aaron832 suggests to disable the confirmation.

**Comment by jgbillings** [comment]
Actually I was looking at the documentation here: 

* http://kanboard.net/documentation/closing-tasks

Which mentions two ways to close tasks. I found a third way, from the column drop down menu, there is an option to close all tasks in the column which is not exactly what I wanted, since there are a few tasks I wanted to keep there, but it is helpful when a lot of a done tasks accumulate.

**Comment by CoMPaTech** [comment]
Another way is to have an extra column named auto-close or whatever and an automatic action; if moved to column 'auto-close' close the issue.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
