### ISSUE TITLE
notifications for subtasks

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1263]
am I missing something? We **don't** get notified if a subtask is assigned. I thought that's a feature already.

**Comment by fguillot** [comment]
There are notifications for subtask modifications.

**Comment by nztebs** [comment]
I have the challenge that if someone owns a task, then creates a subtask and assigns it to me, I don't receive the notification - because I'm not assigned to the TASK and I've only got my notification settings on for tasks I'm assigned, instead of all tasks. (I don't want an email for every task that gets modified - we have a lot of activity on our kanboards!)  As far as I can see in the settings, I can't have it configured to notify me of a new subtask assigned to me.  Is that correct?

**Comment by fguillot** [comment]
@nztebs correct, that need to be improved.

**Comment by nztebs** [comment]
Cool - thanks for confirming. :)  I'll watch for comments in future updates.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
