### ISSUE TITLE
show closed tasks in readonly / public view

### ISSUE THREAD

**Issue by sebastiantiede** [kanboard/kanboard#1360]
Hi,

Is there a way to show closed tasks in the readonly / public view?

Thanks in advance
Sebastian

**Comment by fguillot** [comment]
Nope

**Comment by fguillot** [comment]
Why do you need that?

**Comment by sebastiantiede** [comment]
The public view is used by the whole team and not all team members have write access to the board.
I don’t see a reason why we should deprive these informations to public users. 
And to prevent the question: "Why should we pay for this, there are no completed tasks?" ;)

**Comment by oxydron** [comment]
I think that different write/read access levels necessary, but only two: administrator and users.
And a administrator can freeze any task, preventing that will changed, deleted or anything.

**Comment by mrfyx** [comment]
+1 to show closed task on the public access. All users in my team have read/write access. Other managers want to see the tasks. Thus, they can suggest tasks or verify the contents of a task.
 However, without the closed tasks, we waste time with "did you do that ? where is the important task we already talking about ? etc" because the task is done/closed and disappears in the public view.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
