### ISSUE TITLE
Place where PO can manage Stories/Epics

### ISSUE THREAD

**Issue by xavividal** [kanboard/kanboard#1543]
Instead of populating the board with hundreds of stories/tasks, could be useful to have a separate listing where we can have the "big" backlog and move from there the stories/tasks we want to do on the board.

**Comment by Busfreak** [comment]
You could use an additional board to manage stories as a backlog and move the task you want to work on to your actual board.

**Comment by xavividal** [comment]
True, but it looks weird to have a board only for listing purposes. Thx.

**Comment by iPublicis** [comment]
+1

**Comment by kwijk** [comment]
Backlogs are typically used in projects to record (and prioritize) items that are not part of a project planning yet, but will be addressed at a later time.

Idea: Add a 'special' backlog column to the board. One that spans all rows (swimlanes). 
- Items on the Backlog are not used in analytics: they are not yet part of a planning
- Items on the backlog can be assigned to a swimlane by drag & drop, so that they become part of a planning
- The backlog column can be hidden, for projects that do not want to use one.

![backlog mockup](https://cloud.githubusercontent.com/assets/12728041/13704176/d643d29a-e79a-11e5-8d95-0706e9851144.png)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
