### ISSUE TITLE
Project Manager option on each card?

### ISSUE THREAD

**Issue by masurti** [kanboard/kanboard#1637]
We have been testing it to see if we are able to utilise it in our IS department.  We plan to use it to manage the development workload for the IS department as a whole.

So we have set-up one big project and have tickets against each developer.  This works well except for the fact that we also need to assign a project manager as well as the person assigned to do to the task on each ticket so that it can be tracked.

Obviously the assignee option is there but is there anyway to also add a Project manager to each ticket?

If not, can we add this as a feature request?

Your help is very much appreciated.

Regards

**Comment by bdrayer** [comment]
Hi,

Because it's perhaps not an ALL USERS need, it would perhaps be more interesting to add this as a Plugin.

There will be many advantage on this. The first one is to resolve the need of this ticket, the second is to make a plugin that will allow people to use it as a base (to develop an other plugin) for other special requirements.

Regards

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
