### ISSUE TITLE
[FR] MS SQL Server backend

### ISSUE THREAD

**Issue by neurocis** [kanboard/kanboard#1649]
Add ability to use MS SQL Server as a database backend.

**Comment by neurocis** [comment]
Bump to this, this may be possible as a funded feature request and am investigating. In the meantime I have kicked out a small token bounty on [Bountysource](https://www.bountysource.com/issues/29811016-fr-ms-sql-server-backend).

**Comment by levlaz** [comment]
I want to work on this. @fguillot I can see a lot of potential future issues, would it make more sense to make this into a plugin?

**Comment by fguillot** [comment]
@levlaz Before to add the support of MS SQL in Kanboard, the database library (PicoDB) have to be tested against the current version of MS SQL.

I'm ok with a plugin, however the database provider class probably need to be modified.

**Comment by levlaz** [comment]
Sounds great. I have Windows 2008 R2 server that i sometimes use for development. It has the last three versions of MS SQL installed so I would be glad to make sure picoDB works.

The plugin approach kind of creates a catch 22 since you need to "install" kanboard first before installing additional plugins.

I guess it may not be a huge deal to temporarily have a SQLite database. In addition I suppose users could also install the plugin the old way.

**Comment by fguillot** [comment]
People can always extract the plugin in the same time they install Kanboard. Installing plugins from the UI is not mandatory because this feature can disabled.

**Comment by fguillot** [comment]
After all this time, I didn't plan to add MS SQL server support. If anyone if interested by this feature, pull-requests are welcome.
