### ISSUE TITLE
unable to login as admin/admin after installation

### ISSUE THREAD

**Issue by Superman1001** [kanboard/kanboard#189]
it always show "The username is required" and "The password is required" even if i fill admin admin

**Comment by naught101** [comment]
I'm also seeing this with the latest git version, apache 2.2.16, PHP 5.3.3, debian sid.

**Comment by HKsAdad** [comment]
I hit the same case today and fixed it by adding necessary permission to the directory in session.save_path because the result from is_writable(session_save_path()) showed FALSE for unknown reason but session file can still be written by PHP.

Hope this helps!

**Comment by stlorenz** [comment]
I ran into the same issue today.
Tried:

PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 

and 
PHP 5.6.20-1+deb.sury.org~trusty+1 (cli) 
 on ubuntu 14.04 LTS

neither with sqlite nor with postgres a login is possible.

**Comment by Q-Storm** [comment]
I have the same issue today
 Centos7, PHP 5.4.16, and sqlite.

I tried the http://kanboard.net/kanboard-latest.zip and git repo both did not work

**Comment by securedirective** [comment]
Despite this issue being marked as Closed, it is still occurring...

- Fresh install of CentOS 7, up-to-date.
- nginx 1.10.2
- PHP v5.4.16
- PHP-FPM v5.4.16

The behavior described above occurs on the Stable version and the latest dev cloned right from github. I troubleshot it down to line 42 in `app/Controller/AuthController.php`. `$_POST` shows the username and password there, but `$this->request->getValues()` returns `array ( )`. I don't know Symfony stuff enough to know why that is occurring.

This issue is still around after 2.5 years. :( I was really looking forward to using your product in my team this next week, but I can't even get it to run the first time.

**Comment by securedirective** [comment]
Oh, and I figure you'll probably ask... yes, I verified the `data` directory is writable. Even turned off selinux temporarily to see if that was the problem. PHP's session.save_path is `/tmp` which is already writable by all users, so I don't see how that could be causing this issue.
