### ISSUE TITLE
BUG? "Unable to migrate database schema" after update

### ISSUE THREAD

**Issue by adilbo** [kanboard/kanboard#1897]
### Expected behaviour
I want to Update my Kanboard Version and did it like discribed here: 
http://kanboard.net/documentation/update

### Actual behaviour
That happens instead:
Internal Error: Unable to migrate database schema: \Schema\version_47 => SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'description'

### Configuration
- Kanboard version: Newest
- Database type and version: mySQL
- PHP version: 5.x
- OS: linux
- Browser: chrome

**Comment by fguillot** [comment]
From which version of Kanboard are you upgrading?

**Comment by adilbo** [comment]
I try to check it and found that db_driver is mysql - is there a place i can see it in the DB?

The only Files i have from the old Version are the config.php and the data Folder - i know that wasn't a good idea ;(

**Comment by adilbo** [comment]
Is there anything i can do to help finding the problem?

**Comment by fguillot** [comment]
From which version did you try to upgrade?

**Comment by adilbo** [comment]
Where in the mySQL db can i see the version? The files in the htdocs folder are already overwritten with the newest from your server ;(

**Comment by adilbo** [comment]
found an backup - updatet from version v3.3

**Comment by adilbo** [comment]
Sorry, still need a solution - updatet from version v3.3. and system show error:

Internal Error: Unable to migrate database schema: \Schema\version_47 => SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'description'

Any news? Thanks for your Help!!

**Comment by adilbo** [comment]
defined('APP_VERSION') or define('APP_VERSION', '1.0.12');

Copyed back my old Files but it dosn't work anymore - think that the Update try to convert the mySQL db.

Realy need help, need the informations from the Board since 25 Feb. and looking to phpmyadmin is not so easy ;)

Thanks a lot

**Comment by fguillot** [comment]
You don't really the choice to fix the schema manually by looking at each migrations.

**Comment by adilbo** [comment]
https://github.com/kanboard/kanboard/issues/1897

6 Month no help, and now closed? Sorry, but no way to get my Data back? 

Thats more than frustrating!

**Comment by fguillot** [comment]
Sorry for closing the issue but I thought that the problem was solved since the time. Due to the amount of tickets, sometimes it can very difficult to help people individually, especially when you have few details about the problem/the configuration used or when I'm not able to reproduce the problem.

Your data is not lost, however you have to manipulate the schema of your database manually to make it work again.

- The error message said that migration 47 doesn't work because it's was already executed. (see https://github.com/kanboard/kanboard/blob/master/app/Schema/Mysql.php#L748)
- You have to check to version number in the table "schema_version".
- Maybe your are stuck at version 46 whatever reason, change manually to the value to 47 and refresh the page that should execute the rest of the migrations.
