### ISSUE TITLE
subtask_time_tracking.time_spent column is not updated when sub-tasks is edited

### ISSUE THREAD

**Issue by oparoz** [kanboard/kanboard#2135]
### Expected behaviour

The time spent column in the subtask_time_tracking table should be updated to match the time_spent column in the subtasks table, because the former is being used to calculate costs
### Actual behaviour

The value in that column is left at 0
### Steps to reproduce
1. Add a sub-tasks
2. Close it
3. Edit it and add that it took 2 hours to complete
4. Look at the time spent column in the subtask_time_tracking table
### Configuration

Application version: 1.0.27
PHP version: 5.6.20
PHP SAPI: fpm-fcgi
OS version: FreeBSD 9.3
Database driver: mysql
Database version: 10.0.23-MariaDB-log

**Comment by aweisshh** [comment]
I would like to add a remark:
At the moment (i think) sometimes the mentioned 'Time spent' gets overwritten by the sum of 'Time tracking'.
The 'Time tracking' feature is used with 'Start Timer' and 'Stop Timer' for every subtask, recorded
to the table 'subtask_time_tracking' with exact begin and end timestamp. 

It seems a little unclear how those two data sources are combined or (not). I would like do do some accounting like this:
- User A spent 5 hours  on (sub-)task X at day Y 
- User A spent 3 hours on (sub-)task X on Day Z... and so on

Which way is the 'right one'? 
-  'Time spent' -> into table 'subtask_time_tracking' as suggested above,
- or Entries from 'subtask_time_tracking' to 'Time spent'. (Which I would prefer because of more accurate accounting)
- or 'Time spent' is a Placeholder if no 'subtask_time_tracking' entries are recorded

**Comment by oparoz** [comment]
From my pov, the subtasks table should be the reference. The value should be either what the PM has entered if larger than what is in `subtask_time_tracking.time_spent` or what was calculated by the timer for all other cases. And the budget plugin should be updated to track the field in subtasks.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
