### ISSUE TITLE
Session logged out after inactivity

### ISSUE THREAD

**Issue by adibudeen** [kanboard/kanboard#217]
I'm not sure if this is by design or not, but after a period of inactivity, kanboard logs me out and forces me to re-enter login information. Even when I select "remember me", it still does the same thing. It also happens whether I use the standard login method or use a Google account. In settings, it still says I have "persistent connections". Does that not mean it should remember that I'm logged in?

**Comment by RobTranquillo** [comment]
I use Version 1.0.43 (April 2017) and still have this Problem.
The Software runs on uberspace.de, an provider that uses CentOS, since end of 2016. 
I like kanboard realy much, but it is realy annoying to get logged out every couple of minutes.
Sometimes its not so easy to get logged in after that. All further kanboard pages are not more able to get loaded. Its necessary to load the root of the kanboard instance to get a login page again.
