### ISSUE TITLE
Inline Avatar image size

### ISSUE THREAD

**Issue by pjrk** [kanboard/kanboard#2172]
The avatars are displayed extremely small (20px) in the board view. An option to make them appear bigger would be great.

**Comment by Cartal156** [comment]
Options like that should be great :
- small (20px) - for those who have very good eyes.
- medium (28px) - default option.
- big (36px) - for those who like "big" images.

Allow to have rounded OR squared images could be a good idea (like those on github).

**Comment by nekohayo** [comment]
For storage, don't provide options or pre-processed resizing, just leave them at the large native sizes and let the browser/CSS handle the scaling dynamically; that way it's going to be of much higher quality and hiDPI-compatible (ex: retina screens).

**Comment by zarizahra** [comment]
+1 please - the small avatars are difficult to use as visual cues in any sort of milestone or list view

**Comment by razron** [comment]
+1 and I agree with nekohayo suggestion.

**Comment by nekohayo** [comment]
Oh, I probably need to clarify a bit my previous comment regarding one particular corner case (where some non-tech-savvy users might upload insane 8 megapixel images as avatars and expect the system to handle them): by native size I actually mean "a single generous size, but not humongous". So something like 512x512 would be a decent resizing+storage size compromise *if* the source image is significantly bigger than that. But for uploaded JPEG images below ~1024x1024 pixels, basically leave them untouched because it's not worth the quality loss vs storage size tradeoff.

The essence of my initial comment remains valid: keep only one "good quality/resolution" version in store and let the browsers handle the resizing on the fly, losslessly.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
