### ISSUE TITLE
Ability to set due dates for subtasks

### ISSUE THREAD

**Issue by adgu** [kanboard/kanboard#2347]
I think the functionality of Kanboard would be greatly improved if there was an option of adding a due date for subtasks.

**Comment by szawadski** [comment]
Hello, I agree this would be nice to have. In practice, we are satisfied with one date for the complete task if not too much sub-tasks. If there are too much and we need to be more precise with the schedulling, we create another task.
Nevertheless, if this feature is created, the notation used in Confluence to auto create tasks would be great:

`task_text(free text)  @PIC(username) //due_date(YYMMDD)`

BTW, the field were the sub-task text is written in a bit too short...

**Comment by Jluisito** [comment]
+1 to this feature request. It would be great for complex projects!

**Comment by deliciousbob** [comment]
Hi Frédéric! @fguillot 
That would be absolutely a great feature for a more complex tasks. We are working a lot with your tool and my colleques are very happy with it but that feature was often whished from people in my company.

- It would help us and other people tremendously because if you want to manage subtasks with due dates you have to create a separate project for it with tasks.
- This would lead to a bit more complexity but it helps people to get an better overview over their tasks.

Thank you and kind regards from Austria
Robert

**Comment by pteurope** [comment]
+1
Hi Frederic - This feature will fit our use internally of KanBoard - Maybe adding subtask in the gant chart as well

BR
François

**Comment by eSkiSo** [comment]
+1 This would be a really good thing, tried to make a plugin but cant the field appear on the create subtask modal

**Comment by eSkiSo** [comment]
This is now possible on 1.0.34, addon also already in **Plugins Directory**

**Comment by szawadski** [comment]
Great feature! It has directly been adopted by  our Kanboard users. Thanks
to the contributors.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
