### ISSUE TITLE
Php fatal error in notifyProject() when starting "kanboard worker"

### ISSUE THREAD

**Issue by yakovenkov** [kanboard/kanboard#2406]
There is an error being occured when I executing `kanboard worker` command:

```
PHP Catchable fatal error:  Argument 1 passed to Kanboard\Notification\WebhookNotification::notifyProject() must be of the type array, null given, called in /var/www/kanban/app/Model/ProjectNotificationModel.php on line 34 and defined in /var/www/kanban/app/Notification/WebhookNotification.php on line 36
```

It seems that `WebhookNotification::notifyProject` expects the `$project` to be an array, but `ProjectNotificationModel::sendNotifications` calls it with `$project` as a value.

Here's a patch that fixes this issue (may be the better solution is to remove `array` prefixes for `$project` variable in `Notification/*.php` hooks)

```
diff --git a/app/Model/ProjectNotificationModel.php b/app/Model/ProjectNotificationModel.php
index aeeee4c..583603e 100644
--- a/app/Model/ProjectNotificationModel.php
+++ b/app/Model/ProjectNotificationModel.php
@@ -30,7 +30,7 @@ class ProjectNotificationModel extends Base
         );

         foreach ($types as $type) {
-            $this->projectNotificationTypeModel->getType($type)->notifyProject($project, $event_name, $event_data);
+            $this->projectNotificationTypeModel->getType($type)->notifyProject((array)$project, $event_name, $event_data);
         }
     }
```

**Comment by cdgeelen** [comment]
I encountered the same error today, while running kanboard worker. The PHP Catchable error shows that $project is being passed as null, thus casting it to an array() will not work.

I've narrowed down the problem to the following: Kanboard worker will hold events in the queue, and then process them in the background. When an event is processed (e.g. TaskEvent), the task will be retrieved from the taskFinderModel. There is no check present whether this task (or other object) is still available, probably because there was no timing issue before the background worker.

After retrieving these values, the getProject() call will fail because there is no task present, and thus a null $project will be passed.

I've proposed a fix in my commit.

```
diff --git a/app/Job/NotificationJob.php b/app/Job/NotificationJob.php
index 904a927..907e543 100644
--- a/app/Job/NotificationJob.php
+++ b/app/Job/NotificationJob.php
@@ -58,10 +58,6 @@ class NotificationJob extends BaseJob
     {
         $values = array();
 
-        if (! empty($event['changes'])) {
-            $values['changes'] = $event['changes'];
-        }
-
         switch ($eventObjectName) {
             case 'Kanboard\Event\TaskEvent':
                 $values['task'] = $this->taskFinderModel->getDetails($event['task_id']);
@@ -80,6 +76,13 @@ class NotificationJob extends BaseJob
                 break;
         }
 
+        // Need to use an array filter to remove any unset/null values in $values. This can happen e.g.
+        // when receiving an event for a task, but the task is already removed. This can happen when
+        // using the Kanboard background worker thread.
+        $values = array_filter($values);
+        if (!empty($values) && !empty($event['changes'])) {
+          $values['changes'] = $event['changes'];
+        }
         return $values;
     }
 }
```

**Comment by fguillot** [comment]
Try with the latest version, it should not happen anymore.
