### ISSUE TITLE
Changing the Application URL

### ISSUE THREAD

**Issue by rsliotta** [kanboard/kanboard#2561]
### Expected behaviour

Currently the application URL is http://gitlab.fifthlayer.net:8100/
I tried to make it https://go.fifthlayer.net/kanboard/ so I can run it behind my SSL proxy.
I use the pound reverse proxy.

Tell us what should happen
It did connect, but redirected to /login instead of /kanboard/login

Maybe I need additional documentation but could not find anything on your site that made sense.  Any help would be appreciated.

I have moved many applications under this tool, but it looks like the absolute URL is not taking affect.  Also, I DID restart the container after.
### Configuration

I am running your docker image.

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: master.a1e2b0f1b88ed445a9dd960d9431fdbcf983fb33
PHP version: 5.6.21
PHP SAPI: fpm-fcgi
OS version: Linux 4.6.3-coreos
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0
```

**Comment by fguillot** [comment]
At the moment, the application URL is only used for notifications (email, slack..) to generate links.

As workaround:
1. You can host the application in the same directory as the one in the reverse-proxy ( https://go.fifthlayer.net/kanboard/ -> http://gitlab.fifthlayer.net:8100/kanboard/)
2. Instead of mapping the application to a subdirectory in your reverse-proxy, you can use a subdomain https://kanboard.fifthlayer.net/ -> http://gitlab.fifthlayer.net:8100/

**Comment by rsliotta** [comment]
Frédéric,

Thanks for the quick response.  #1 is preferable.  Do you know this to work for sure or will I be doing Trial / Error?

  
Best Regards,

Bob Liotta
bob.liotta@rsliotta.com
(914) 414 5162

**Comment by fguillot** [comment]
I didn't try it myself but I believe that should work.

**Comment by rsliotta** [comment]
Fair enough….  I will let you know…


Best Regards,

Bob Liotta
bob.liotta@rsliotta.com
(914) 414 5162
