### ISSUE TITLE
Failure running unittest LetterAvatarProviderTest::testRenderWithFullName

### ISSUE THREAD

**Issue by stinnux** [kanboard/kanboard#2583]
### Expected behaviour

Unit Test should run without error
### Actual behaviour

Error when running Unittest LetterAvatarProviderTest::testRenderWithFullName
### Steps to reproduce
1. Run phpunit -c tests\units.sqlite.xml

```
There was 1 failure:

1) LetterAvatarProviderTest::testRenderWithFullName
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="avatar-letter" style="background-color: rgb(120, 83, 58)" title="Kanboard Admin">KA</div>'
+'<div class="avatar-letter" style="background-color: rgb(210, 45, 61)" title="Kanboard Admin">KA</div>'

C:\Users\c5214270\Documents\GitHub\ORIGINAL KANBOARD\kanboard\tests\units\User\Avatar\LetterAvatarProviderTest.php:27

FAILURES!
Tests: 933, Assertions: 53676, Failures: 1.

```
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: current master 
- Database type and version: sqlite
- PHP version: 7.0.9
- OS: Windows 10 x64
- Browser: none

**Comment by fguillot** [comment]
That probably doesn't run on your workstation maybe because you are using PHP compiled in 32bits (see: https://github.com/kanboard/kanboard/blob/master/app/User/Avatar/LetterAvatarProvider.php#L145, PHP_INT_MAX is not the same size in 32 or 64bits).

It's working fine on Unix/Linux (see travis-ci build), unit tests will require some modification to run on Windows/PHP 32bits.
