### ISSUE TITLE
Feature Request: Allow to Print Tasks or download in PDF

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#2650]
### Expected behaviour

Currently no print option or export to PDF for offline working on tasks
### Request

Allow to print task in a presentable format (browser print option includes all menus wrongly laid out etc) or download in PDF format so that we can work on it offline when creating random notes and in meetings etc.
### Configuration
- Kanboard version: 1.0.33

**Comment by erpnedir** [comment]
+1 for this.
I am planning to use KB for production line monitoring. A functionality to print the task, which supports barcode included custom label templates would be super cool.

**Comment by aljawaid** [comment]
@erpnedir Thanks for your reply, if it was simple php or html I'm sure we could find a work around but as a very very basic coder I can't seem to understand how the KB coding structure works.

I also use KB to plan tasks (jobs) and projects (business activities) around my small business and the other day I had a meeting with a guy where I had written/caved all the notes/comments (ideas)/attachments/links with KB only to realise there was no export to pdf or print option so I had to screenshot everything.  The browser (Chrome) print menu created a very crappy layout and all the menus were listed.

I hope there is an feature to add if someone knows how.

**Comment by andreapx** [comment]
+1!
Se need it a looooot!!!

**Comment by valentincollado** [comment]
+1. 
Very important for industrial maintenance, breakdowns, repairs, etc.

**Comment by dehardstyler** [comment]
So guys, I know this is a little late, but maybe I can help someone with it. Please try the following while printing:

Step 1: Install Google Chrome ( don't know the method in another browser ;) ) 
Step 2: Open Developer Mode ( F12 )
Step 3: Click on the menu button, in Developer Mode, and choose "More Tools"
Step 4: Choose "Rendering"
Step 5: At the bottom of the Developer Mode screen look for "Emulate CSS Media" and choose "Screen"
Step 6: *IMPORTANT* Leave Developer Mode open, otherwise it will not work.
Step 7: Ctrl + P to open the print wizard.
Step 8: Choose A3 ( better results ), Landscape, Color, Background Graphics and disable "Headers and Footers" 
Step 9: Have a look at your nicely printed KanBoard page! :-)

**Comment by aljawaid** [comment]
@fguillot You added the `help wanted` label - how can we help?

Was just thinking, even a paper-friendly .css file would help to get us going.

**Comment by creecros** [comment]
Working on this. Mostly done for tasks. Someone with better html/css skills is welcome to improve upon layout. Using dompdf.

https://github.com/creecros/Task2pdf

**Comment by aljawaid** [comment]
Thanks to @creecros for creating this neat plugin https://github.com/creecros/Task2pdf
