### ISSUE TITLE
Duplicating task in another project clear fields: tag and reference

### ISSUE THREAD

**Issue by jarod80** [kanboard/kanboard#2659]
### Expected behaviour

Duplicating a task in another project should duplicate all the information possibile. 
I think the only problematic field could be assigned user because of permission may not be present.
### Actual behaviour

All the information are set but tag and reference field are empty.
### Steps to reproduce
1. Only need to duplicate task in another project with one tag and a field set in references.
   2.
   3.
### Configuration

Application version: 1.0.33 
◾ PHP version: 5.4.45 
◾ PHP SAPI: cgi-fcgi 
◾ OS version: Windows NT 6.2 
◾ Database driver: sqlite 
◾ Database version: 3.8.10.2 
◾ Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Comment by croulibri** [comment]
Hello,
I am facing the same issue and I am very much interested in seeing the duplicated tasks from one project to another one keeping tags and reference.
I've seen it is mentioned as not being duplicated at [https://kanboard.net/documentation/duplicate-move-tasks](https://kanboard.net/documentation/duplicate-move-tasks), but if it is possible to develop this function it will be very useful to me.

**Comment by cornelisdo** [comment]
Hello,
Same for me, we work with hierarchical kanbans and it would be great if all the things such as files linked to the task were copied too.

**Comment by asegu** [comment]
Hi,

I somewhat understand the logic that is behind the scenes - a tag is associated to a project and that  task references the tags. With such an understanding, it could be desired that a task moved to another project doesn't keep tags that don't already exist in that project.

In my environment however, I need the tags to be preserved. Since my issue was with moved tasks, and not duplicated tasks, I opened a separate issue #2817 

I found time to investigate a bit more and made the necessary change to fix my issue. But since already looking at the code, I think I found the limitation for duplication can be removed by changing one line. 

Open the file app/Model/TagDuplicationModel.php, search for "public function duplicateTaskTagsToAnotherProject" and then in that method, change tagModel->getIdByName to be tagModel->findOrCreateTag (uses the same parameters)

Note that I'm not one of the developers of this project nor have I tested the behavior of duplicating tasks with tags between projects (not my use-case). Make the change I suggest with a certain level of caution.

Hope this helps,
Andrew

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
