### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by JLBA** [kanboard/kanboard#2668]
Hi,
Sorry to write this here but I don't find any mail, forum or else to send my question. Here it is.

First, thanks for kanboard which is a great project.

I understand how Kanban and then Kanboard works. But I'm always working with many projects opened at the same time.

So, my idea/question is to have a dashboard where there would be one swimlane by project and in each swimlane the x next undone steps. 

So I could have a quickview of the work waiting to be done and then decide what to do now and just after ad so on…

Clicking on a swimlane or step lead to the project page with it's own swimlanes as actually.

Thanks for your answer.

**Comment by thomastjiLinux** [comment]
Hi JLBA,

You'll might want to follow pull https://github.com/kanboard/kanboard/pull/2624? This pull will make Stinnux's plugin "Bigboard" available where all boards are visible on the same page. 


Kind regards

**Comment by TheCloud** [comment]
Thank you, I was thinking something similar too, but I'm adding a question for WIP.

If I set a WIP limit for a column let's say 2, if I create a swimlane I can "force" this because the limit remains on the default swimlane.
I would instead create a "per column" WIP which sums the tasks for each swim lane.

Infacti with multiple projects you end up with many swimlanes, but that doesn't encrease your WIP power (unless you hire new people when a project is assigned)

**Comment by JLBA** [comment]
Thanks for tour answer. For my understanding, what is WIP please ?

-- 
JL Barts-Andreetto

**Comment by TheCloud** [comment]
WIP is "Work In Progress", the root of the Kanban Board is limiting the number of things (WIP Limit) you can do before pulling another thing to work at.

Kanbard allow to set WIP Limit "per swimlane" column, while it should add it "per project".

**Comment by JLBA** [comment]
"Work in progress" : of course !

My pb is just visual. Each morning, I need to have an overview of all the stuff to be done and forget nothing. And then decide what to do next. And I  was thinking the vertical swimlanes presentation would be more readable. Perhaps with a first one where you drag n' drop what you want to do Today.

-- 
JL Barts-Andreetto
