### ISSUE TITLE
Webinterface fails to display

### ISSUE THREAD

**Issue by axelhuizinga** [kanboard/kanboard#2736]
### Expected behaviour

kanboard interface should display :)
### Actual behaviour

on some! of our openSUSE 13.1 (x86_64) machines
open the webinterface fails with:
Internal Error: Service definition is not a Closure or invokable object.
calling debug_stacktrace at this location gives me:
#0  Pimple\Container->factory() called at [/srv/www/htdocs/kanboard/app/ServiceProvider/ClassProvider.php:164]
#1  Kanboard\ServiceProvider\ClassProvider->register(Pimple\Container Object ([] => Array ([emailClient] =>

$container->register(new Kanboard\ServiceProvider\ClassProvider());

failing to complete the stacktrace with a 
 PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 1088524288 bytes) in /srv/www/htdocs/kanboard/vendor/pimple/pimple/src/Pimple/Container.php on line 162
### Steps to reproduce
1. Install as given in the docs
2. Open the interface in the browser
3. Enjoy a working installation on some machines and this error on some others - same OS - all deps installed on both
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.33
PHP version: 5.4.20
PHP SAPI: apache2handler
OS version: Linux 3.12.53-40-default
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
```

**Comment by fguillot** [comment]
According to your error message, PHP try to allocate a large amount of memory for no valid reason. 

Unfortunately, I cannot really guess where the problem is coming from, especially if you install KB successfully on another machine with exactly the same configuration.

This version of PHP is very old, maybe this is known problem with this version, you could try to upgrade to a more recent version. Disable unnecessary extensions...

Sorry to not be able to help you.
