### ISSUE TITLE
Unable to login more than once on an installation hosted on ipage

### ISSUE THREAD

**Issue by baronir** [kanboard/kanboard#2744]
### Expected behaviour

After a fresh install and configuration for MySQL, I am able to login with admin / admin. However, it would be expected:
- to login with new users on other browsers
- to logout and log in again with the admin user
### Actual behaviour

After some update of the config.php to access the MySQL DB of ipage, I can only once access the kanboard features and go further than the login page. 
After I log out of kanboard, I cannot go further the login page. Every time I try to login (with admin user or other users), I always get back to the login page with the error message "The username is required".

I have tried all the possible fix of the .htaccess file or the config.php file.

Because kanboard is hosted on ipage, I cannot override some feature in apache, and must therefore work with define('ENABLE_URL_REWRITE', false) in config.php.

I have completely re-install kanboard and discovered the same frustrating behaviour. 
A click on sign-in and I am always back to this URL: http://mydomain/kanboard/?controller=AuthController&action=check 
in the browser.
### Steps to reproduce
1. Install last stable revision of kanboard on ipage (mysql db).
   NB : the domain name redirects to a folder of ipage. In this folder is the kanboard folder and also a wordpress installation.
2. Configure the config.php file (connection to ipage mysql_db OK)
3. First sign in with admin / admin works out
4. Try to log in with new user fails
5. Log out with admin and sign in again with admin always fail
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: kanboard-1.0.33
- Database type and version: MySql 5.6.32
- PHP version:  5.6
- OS: Debian
- Browser: Chrome 53.0.2785.143 , same problem with internet explorer, Edge and Firefox

**Comment by rdelje** [comment]
I've the same problem, but installed in a ubuntu server (16.04)....
The install went ok, and I can work, create users, login, logout, etc...
But if I change config.php in any way (tried only to change debug mode to true and log_driver to file) I can log in, but if i log out, i can't log in again... 
I'm triying to set it to use ldap, but can't try more than one one time, after that, every log in (even with admin) the same error.
If I undo the changes on config.php (editing) it works again...

After more play, i think the problem is went i put log_driver to 'file', with syslog, it works fine.

log file: 
[2016-11-16 10:34:55] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
[2016-11-16 10:34:55] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2016-11-16 10:34:55] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
[2016-11-16 10:34:55] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\AuthController::check

Kanboard version: 1.0.34
OS: Ubuntu 16.04
PHP: 7.0
mysql 10
browser: firefox 49, edge, internet explorer 11

**Comment by fguillot** [comment]
Can you try again with Kanboard 1.0.38? (Your issue might be related to your hosting provider.)

**Comment by baronir** [comment]
Hello, yes, I will do my best to try it in the coming days, as it would be useful knowledge for the community.

In the meantime I have installed kanboard on a local machine, combined with a no_ip account, and it works fine.

Thanks for the great work you are doing !
