### ISSUE TITLE
Is adding files / notices to a project possible?

### ISSUE THREAD

**Issue by k00ni** [kanboard/kanboard#2747]
First of all, thanks for this piece of software, very nice!

I am currently evaluating if Kanboard can be my organizer. What currently is missing is file/note storage in some way. No matter if virtual or actual files, but adding text (e.g. meeting notes) to a project (or swim lane) would be very nice.

There is a function to add documents to a task. But it would require that the task for instance is about a meeting, so i can add my notes as a file to it. But this is kinda confusing and ineffective. Another thought: if i want to attach documents about specifications, UI sketches, ... i also need to do it by mis-using a task.

Is there already a hidden function to solve my request? What you think about it?

**Comment by marcosaccioly** [comment]
Hey, k00ni. This is already available at the project page when you choose "project overview" instead of "board view". See the printscreen below. There you have an option to add a description and to upload files. 

The URL for it is /?controller=ProjectOverview&action=show&project_id=XX, where XX is the project ID. 

![project_view](https://cloud.githubusercontent.com/assets/1198117/19350658/083fbae6-912f-11e6-816d-57da6e83fccd.jpg)

Hope it helps,

**Comment by k00ni** [comment]
Hi @marcosaccioly, thanks for the hint! That is basically what i searched for. Its kinda centralized, but for now sufficient. 

Do you know if there are any thoughts towards a more advanced file/content management? (connecting OwnCloud/Nextcloud or something like that?)

**Comment by marcosaccioly** [comment]
@k00ni I wouldn't know about that, but it's great that you can now upload your files. Cheers!

**Comment by helfreire** [comment]
@marcosaccioly Obrigado.
