### ISSUE TITLE
SQLite to MySQL migration

### ISSUE THREAD

**Issue by rverchere** [kanboard/kanboard#2756]
Hello,

I'm using kanboard with a sqlite db, but we use the tool more and more.
Do you have any idea how I can migrate the database to a mysql server?

Thanks!

**Comment by rverchere** [comment]
I've just tried some script migration (https://www.vincentliefooghe.net/content/owncloud-convertir-la-base-sqlite-%C3%A0-mysql), but cannot add the dump :

`ERROR 1101 (42000) at line 2: BLOB/TEXT column 'role' can't have a default value`

**Comment by fourier** [comment]
Yes please, the same for us: we feel limited by Sqlite now. Is there any guide how painlessly migrate to the MySql or postgress ?

**Comment by oliviermaridat** [comment]
I have written a script for this: https://github.com/oliviermaridat/kanboard-sqlite2mysql. With a the Kanboard version of April 20116 it was working very well. It should still work, try it and let me know if you have any issue (not there but directly in the kanboard-sqlite2mysql script).

The only difficult part is when database column names are changed because SQLite does not allow to remove the previous column, therefore, we have to add these old column name to the new MySQL database, before to import the SQLite database in it.

If some column names have been changed since April, the script will not work properly. But the logs may tell you the issue and the fix to apply on the script.

**Comment by rverchere** [comment]
@oliviermaridat it works fine with v1.0.34, with some minor modification (Pull request on going).

Thanks!

**Comment by gerhard-tinned** [comment]
+1
Would love to see a migration path as part of the project. Maybe via the cli?

**Comment by fguillot** [comment]
For now, having those migration scripts included in KB is not planned. You will have to use custom scripts.
