### ISSUE TITLE
JSON API searchTasks does not return same objects as getAllTasks

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2783]
### Expected behaviour

When a task is returned from API the object should be of same structure/consistent for any function kanboard wide.
### Actual behaviour

SearchTasks return number of comments, of documents but does not return color object with rgb codes, instead returns color name 

GetAllTasks returns no information about comments and files, but returns color object with rgb codes and color name for css use.
### Configuration
- Kanboard version: current
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by markjszy** [comment]
After looking at TaskProcedure.php, it looks like the behavioral difference is due to some methods using the Lexer facilities for retrieval while others use the taskFinderModel facilities. 

@fguillot , do you see this as a broader task that requires normalization across the API in this regard, or would you prefer that just this one particular instance be addressed? I was thinking of working on this issue.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
