### ISSUE TITLE
Create a Task for a Group

### ISSUE THREAD

**Issue by supportreq** [kanboard/kanboard#2815]
### Expected behaviour

Currently we are able to assign a task to an individual person, we have groups assigned for a project. It is not allowing to select the group for a task

### Actual behaviour

It should allow to select which group the task is being created to.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.34
- Database type and version: SQLite
- PHP version: 5.6
- OS: Linux
- Browser: Firefox

**Comment by isAAAc** [comment]
+1

**Comment by orware** [comment]
Related to this feature request: I don't necessarily need the group option myself, but something that would be nice is that if in addition to the assignee, we could specify a list of additional users that should be kept "in the loop" as the item is being worked on.

Use cases:

- I currently operate within my own project in Kanboard, but occasionally I work on tasks that are related to our network/server folks and I'd like to keep them in the loop just for these tasks (since they aren't subscribed to my project's notifications). I'd like to be able to specify them to be notified as well (or perhaps as a group, but we're not actually using groups ourselves much at the moment).
- If I'm working on a task for a specific user on campus, it would be nice to include them so they can be notified as I'm working on things for them too.

**Comment by Ba-zi** [comment]
I strongly support that request and I want to add another use case:
We have a kanboard project where every user can create a task in the first column. As soon as he's done with describing what he wants to do, he drops the task in the second column "to check". At that point a certain group that have budget legitimation needs to decide if that task can be done by the requester or not. Therefore it would be beneficial to automatically assign it to the group.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
