### ISSUE TITLE
Strange behavior with task creation (only!) on shared hosting (only!)

### ISSUE THREAD

**Issue by uriel1998** [kanboard/kanboard#2895]
### Expected behaviour

Present task creation dialog when pressing + button on Kanban boards and to save new task when created via menu dropdown.

### Steps to reproduce

Installed 1.0.35 of Kanboard. PHP 5.6 (though also when I changed it to PHP 7) with dependencies installed on shared hosting account.  
Created a user and project. Could not click on + sign on Kanban boards to create task. Menu dropdown allowed me to choose "Create task", but hung on actual creation. Behavior persists with both MySQL and SQLite.  

Installed on local computer running Debian Jessie and Apache2 using SQLite. Works out of box (but my home server is not appropriate for this use-case).  Copy SQLite db to shared hosting, and I can duplicate tasks and create sub-tasks, but still cannot _create_ a new task.  No obvious PHP errors.  Debug log attached where I duplicated the task, then tried to create a new one (line 580) before canceling it out.

PHP modules and configuration are almost identical on the two - the shared hosting server has 

enable_post_data_reading
expose_php
display_errors

all switched on.

Any assistance (or ideas even where to start looking here) would be appreciated.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.35
PHP version: 5.6.28
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
Database driver: sqlite
Database version: 3.8.5
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
[debug.log.txt](https://github.com/kanboard/kanboard/files/656491/debug.log.txt)

**Comment by LinuxLowell** [comment]
+1

Having the same issue... back to post it notes on my desk for the time being.

**Comment by uriel1998** [comment]
Glad to see I'm not the only one.  To reiterate, the software (literally
identical installs from the same archive file) behaves exactly as expected
on my Debian Jessie box and my OS X Snow Leopard box (with macports
installed PHP).  I install it in exactly the same way on shared hosting,
and the software goes pooft as above.

**Comment by LinuxLowell** [comment]
I have only tested in a shared environment.  It was running like champ for months but changed providers a few weeks ago.  I was performing cleanup yesterday.  As part of that cleanup I was able to close a lot of tasks and even update tasks.  However, I was not able to create tasks.  I think yesterday was the first time I tried to add tasks since the migration.

**Behavior**
- When mousing over the "+" sign at the top the column, it turns red.  When I click the "+", nothing happens. 
- When selecting "Add new task" in the menu, I get the create task dialog. I can complete it but when I hit  the "Save" bottom, I just get the animated wheel and "Saving" (_pic below_).  I've let it run for quite some time.  I have to hit cancel and KB runs normally.
![create_issue](https://cloud.githubusercontent.com/assets/24941597/21725417/35bb533a-d3ed-11e6-9c11-5d60276435e1.png)
- Tried "Create tasks in bulk" at the top of each column.  Nothing happens when I click the option.

**Attempted Troubleshooting**
- Tried multiple projects with the same result
- Upgraded from 1.0.34 to 1.0.36 - no change
- chmod the SQLite db from 644 to 777 - no change

**Comment by LinuxLowell** [comment]
So for kicks and grins (and I'm getting desperate) I also tried the following:

- Tried in a different browser - this time IceCat (Firefox derivative) just to make sure it wasn't webkit causing the problem.
- Changed the server PHP version to 7.0

`

    Application version: 1.0.36
    PHP version: 7.0.14
    PHP SAPI: cgi-fcgi
    OS version: Linux 2.6.32-673.26.1.lve1.4.18.el6.x86_64
    Database driver: sqlite
    Database version: 3.8.5
    Browser: Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0

`
Neither fixed the problem.  I notice the browser user agent reports as Windows.. interesting as I'm running Arch Linux on the desktop.

**Comment by zaShadow** [comment]
+ 1

I can't create new tasks

Exactly the same behaviour as described by @LinuxLowell

**Comment by LinuxLowell** [comment]
Starting using "Deck" which is a NextCloud app.  Don't like it as much so I thought I'd check back and see if this issue had been addressed.  

I installed 1.0.43 and the problem remains.  The behavior changed a little bit when "Add new task".  When I hit "Save" instead of getting the indefinitely spinning "working" icon, it goes away after a few second and returns the the Add Task dialogue.  The task was not saved. Other than that, behvior is identical to what I described above. 

If this is indeed a php/server config issue some pointers on things to check would be greatly appreciated.  I've gone through the recommended prereq's and install directions in the docs line by line and everything looks good.

**Comment by rautamiekka** [comment]
^ Available PHP versions and used OS release ?

**Comment by LinuxLowell** [comment]
@rautamiekka Not sure I understand the comment/ask.  I've already outlined above versions I've tested.  OS as well.  (Look at my 9 Jan comment.)

**Comment by fguillot** [comment]
- Check the Apache logs for errors
- Check the browser console
- Check if you have mod_security enabled
- Check if all permissions are correct

**Comment by fguillot** [comment]
Closing stale issue.
