### ISSUE TITLE
Feature Request: make Swimlanes have a background color

### ISSUE THREAD

**Issue by aslmx** [kanboard/kanboard#2913]
### Expected behaviour

Swimlanes can be defined with Background colors

### Actual behaviour

Swimlanes are simply white
There are automatic actions to change the colors of tasks when changing the swimlane, but thats it..

**Comment by achimace** [comment]
This would be a valuable property for me as well.

**Comment by sjlovell** [comment]
would find this very useful too!

**Comment by fguillot** [comment]
Why is it really necessary?

**Comment by dhornford** [comment]
Nicer visualization of banding
Especially when threes a long list of cards in a column

-- 
Dave Hornford
Conexiam. Straightforward answers to complex problems.
www.conexiam.com | +1.403.818.4303

On June 3, 2017 at 4:46:50 PM, Frédéric Guillot (notifications@github.com)
wrote:

Why is it really necessary?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanboard/kanboard/issues/2913#issuecomment-306005955>,
or mute the thread

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
