### ISSUE TITLE
If a plugin causes an internal error, identify the faulty plugin

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#2919]
```
$ git remote update && git checkout v1.0.36 && php ~/composer.phar install --no-dev
Previous HEAD position was 4badb84...
HEAD is now at d49ce63...

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 3 installs, 12 updates, 1 removal
  - Removing symfony/stopwatch (v2.8.4)
  - Updating christian-riesen/base32 (1.2.2 => 1.3.1) Loading from cache
  - Updating christian-riesen/otp (1.4 => 1.4.3) Loading from cache
  - Updating eluceo/ical (0.8.0 => 0.10.1) Loading from cache
  - Updating fguillot/json-rpc (v1.0.3 => v1.2.1) Checking out d491bb549b
  - Updating fguillot/picodb (v1.0.8 => v1.0.14) Checking out 86a831302a
  - Updating fguillot/simple-validator (1.0.0 => v1.0.1) Checking out 23b0a99c5f
  - Updating fguillot/simplelogger (v1.0.0 => v1.0.1) Checking out c683184119
  - Updating paragonie/random_compat (v2.0.1 => v2.0.2) Loading from cache
  - Updating swiftmailer/swiftmailer (v5.4.1 => v5.4.2) Loading from cache
  - Updating symfony/polyfill-mbstring (v1.1.1 => v1.2.0) Loading from cache
  - Updating symfony/console (v2.8.4 => v2.8.7) Loading from cache
  - Updating symfony/event-dispatcher (v2.8.4 => v2.7.14) Loading from cache
  - Installing zendframework/zendxml (1.0.2) Loading from cache
  - Installing fguillot/picofeed (v0.1.24) Loading from cache
  - Installing fguillot/simple-queue (v1.0.1) Loading from cache
Generating optimized autoload files

$ git status
nothing to commit (working directory clean)
```

However when I visit the kanboard web instance, I get:

> Internal Error: Identifier "config" is not defined.

I didn't know why... another kanboard instance I upgraded from the same version tag (v1.0.27) had no such problem. Comparing the two directories with "diff", I saw no difference either.

**Comment by nekohayo** [comment]
Ah, I found the issue: I had to go into the plugins/GoogleAuth directory and do a git remote update && git checkout v1.0.3

So I guess the essence of this bug report could now be: in situations where a plugin raises a fatal error like that, Kanboard should clearly indicate that it's plugin $foobar causing the problem.

**Comment by fguillot** [comment]
Each plugin have the responsibility the define their compatibility with the installed version Kanboard. When plugins are not compatible they are listed as such on the plugins page.

Since PHP is a shitty programming language, I cannot catch all errors that could be generated by plugins.

At the end of the day, you should not update blindly your installation. You should always check that each installed plugin is compatible. (and of course, check the ChangeLog for breaking changes).

I know that this is not perfect, but the plugin implementation is more like a hack to satisfy the increasing demand of new features.
