### ISSUE TITLE
Option to change default start page

### ISSUE THREAD

**Issue by rverchere** [kanboard/kanboard#2969]
### Actual behaviour

When I log in, I am always redirected to the dashboard page.
I would like to add a parameter to make configurable the start page, to select either the dashboard, or a project in particular.

### Wanted behaviour

Once startup option configured, user could be automatically redirected to the project set up.

### Configuration

- Kanboard version: 1.0.34
- Database type and version: mysql 5.5.53-0+deb7u1
- PHP version: 5.4.45-0+deb7u6
- OS: GNU/Linux Debian
- Browser: Mozilla Firefow

**Comment by fguillot** [comment]
Is it really necessary to implement such feature?

**Comment by levlaz** [comment]
I use kanboard for multiple organizations and have about a dozen project boards. My solution to this is to create a bookmark for the boards that I care about in different browser profiles (I have one for work, personal dev, and side projects).

This feature would not really help me because I want my "home" board to be different depending on the context that I am in at the given moment.

**Comment by rverchere** [comment]
@fguillot as you want, it's a minor feature that could help me, but it's your project ;)

If I **really** want it, I could try fork and develop the option by myself.

**Comment by levlaz** [comment]
Don't take it the wrong way. 100 minor features turn into bloated, complex  and unmaintainable software. I think he's just trying to make sure that this is valid and necessary feature.

**Comment by rverchere** [comment]
@levlaz I just edit my navigator bookmark with the direct link to my default project, it does the job! No pb to not implement this feature, and thanks again for you work!
