### ISSUE TITLE
Error migration to 122

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#3060]
When I update on latest GIT version migration DB is not working.

When I run manually, follow line does not work:

```
ALTER TABLE tasks ADD CONSTRAINT tasks_swimlane_ibfk_1 FOREIGN KEY (swimlane_id) REFERENCES swimlanes(id) ON DELETE CASCADE;
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`kanboard`.`#sql-a20_5419`, CONSTRAINT `tasks_swimlane_ibfk_1` FOREIGN KEY (`swimlane_id`) REFERENCES `swimlanes` (`id`) ON DELETE CASCADE)
```

**Comment by fguillot** [comment]
- Is this the only SQL query that fail in migration 122? the other one are working properly?
- Which version of Mysql are you using?

**Comment by fguillot** [comment]
I updated the Mysql migration, can you try again if you still of version 121?

**Comment by Kolesar** [comment]
I tried only on MySQL, I do not know what is with another DBs

I tried again, but I get same error in browser:
```
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (You may have to fix it manually)
```

MySQL Version: '5.6.35'

**Comment by fguillot** [comment]
This is not the same error. What did you do the first time that fail? did you try to run SQL query manually?

**Comment by Busfreak** [comment]
Hi!

I cloned my installation (about two years of data) to test.
I tried with the nightly build and it gave the error:
`Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[HY000]: General error: 1093 You can't specify target table 'action_has_params' for update in FROM clause (You may have to fix it manually)`
With the current master all works fine, because Fréderic fixed this with the last commit.

With a second clone I tested running all 'ALTER TABLE' statements manually. This throws error
`Cannot add or update a child row: a foreign key constraint fails (`kanboard1`.`#sql-4b6_101a8`, CONSTRAINT `tasks_swimlane_ibfk_1` FOREIGN KEY (`swimlane_id`) REFERENCES `swimlanes` (`id`) ON DELETE CASCADE)`
because not all tasks:swimlane_id have a partner in swimlanes:id, so constraint fails.

Preventing this the function migrate_default_swimlane in Schema\Migration.php has to run first. And this throws your last error, I think
`Integrity constraint violation: 1048 Column 'name' cannot be null (You may have to fix it manually)`

Maybe you should have a look into your database, if all projects have an entry in the column 'default_swimlane'.

**Comment by fguillot** [comment]
@Busfreak I fixed the first error in this commit: https://github.com/kanboard/kanboard/commit/3d7a682ec794b7485fc979ca910e22c6438a3c26

If you retry with a fresh copy of your database, it should work?

**Comment by Busfreak** [comment]
Hi Fréderic!
Yes, fresh copy from database with git-clone after that commit migrated without problems.

One possible problem I think about is that for the new constraint in table tasks you have to do changes in the database schema. This is done in Migration.php. BUT in the table swimlanes the column name has to be NOT NULL. The data for this column you get from $project['default_swimlane'] and THIS can be NULL.
Its only an idee 😄 

Martin

**Comment by Kolesar** [comment]
Hi Fréderic,

First time when I tried to update to latest version (via git pull) I got message in browser same as @Busfreak 

> Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[HY000]: General error: 1093 You can't specify target table 'action_has_params' for update in FROM clause (You may have to fix it manually)

When I tried to update DB manually from version_122, three ALTERS works, except last:
> ALTER TABLE tasks ADD CONSTRAINT tasks_swimlane_ibfk_1 FOREIGN KEY (swimlane_id) REFERENCES swimlanes(id) ON DELETE CASCADE

And in browser I get error like I wrote before
> Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (You may have to fix it manually)

I pull latest code and try automatically (just refresh my KB :) ), but I get same error with ...'name' cannot be null...

And again, I tried manually latest ALTER, I get same error.

Maybe I should manually change something more in my DB? Some another ALTER or, ...?

**Comment by fguillot** [comment]
@Kolesar So it fail here: https://github.com/kanboard/kanboard/blob/master/app/Schema/Migration.php#L17

Do you have entries with the column "default_swimlane" at NULL in the table projects? (before to run the migration)

**Comment by Busfreak** [comment]
I tested again with a new clone, KB 1.0.39, schema version 121.

Setting one entry in table projects in column default_swimlane to NULL and _then_ updating KB source to master leads to the error mentioned above:

> Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (You may have to fix it manually)

So, @Kolesar did you check your database?

**Comment by Kolesar** [comment]
As I can see this is my mistake here.

First, when I get error:
```
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[HY000]: General error: 1093 You can't specify target table 'action_has_params' for update in FROM clause (You may have to fix it manually)
```

I started migration manually, but forgot run first queries from Migration.php file.

So, for now, from my perspective, you can close this issue. Thanks for support.
