### ISSUE TITLE
show public board in iframe

### ISSUE THREAD

**Issue by remrem** [kanboard/kanboard#309]
Hi,
I want to show a public board in iframe but I can't ...
any solution ?

board at : http://example1.com/kanboard/?controller=board&action=readonly&token=...
iframe in : http://example2.com/show_work_in_progress.html

Thanks ;)

**Comment by frederikheld** [comment]
Hey Frédéric,

it would be great if this would also be possible for the whole kanboard (not only public boards). I would like to embed Kanboard in my OnwCloud installation via the external link option in OC.

I assume that it is easier for the user to access all applications directly from the OC menu instead of having a link for every application.

Thanks for your gread work on this project!

Best regards
Frederik
