### ISSUE TITLE
Unable to import tasks from exported CSV

### ISSUE THREAD

**Issue by yannicka** [kanboard/kanboard#3107]
### Actual behaviour

When I try to import a CSV on my Kanboard instance, I've the following error:

`Rien n'a été importé` (or `Nothing have been imported!` in english).

### Expected behaviour

I want the tasks to be imported on the new project.

### Steps to reproduce

1. Export tasks from a project
2. Create a new empty project
3. Import tasks on the new project with default configuration (or with "semicolon" separator, in case)

It's the same from an instance to the same instance and from an instance to another instance (e.g. local to local OR framaboard to local).

#### Kanboard

- Kanboard version: 1.0.40
- Database type and version:  mysql 5.7.14-log
- PHP version:  7.0.15
- OS: Linux 3.14.79-grsec-hosting-web-3.14

#### My computer
- OS: Windows 8.1
- Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

If I missed some information, please tell me.

**Comment by rautamiekka** [comment]
I confirm it's exactly like that.

In my case the setup is this, copypasted from the setup status:
- Application version: 1.0.40
- PHP version: 7.0.16-4+deb.sury.org~xenial+1
- PHP SAPI: fpm-fcgi
- OS version: Linux 4.4.0-64-generic
- Database driver: mysql
- Database version: 5.7.17-0ubuntu0.16.04.1
- Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by fguillot** [comment]
The import and exports formats are not the same. That need to be improved.

**Comment by yannicka** [comment]
OK, thanks, that would be great. Maybe add a message temporarily to explain that (or explain what is the problem on import)?

**Comment by dhornford** [comment]
The import & export templates are different
There is additional information and we have noticed the import is very
template sensitive

-- 
Dave Hornford
Conexiam. Straightforward answers to complex problems.
www.conexiam.com | +1.403.818.4303

On March 9, 2017 at 9:19:35 AM, Yannick A. (notifications@github.com) wrote:

Actual behaviour

When I try to import a CSV on my Kanboard instance, I've the following
error:

Rien n'a été importé (or Nothing have been imported! in english).
Expected behaviour

I want the tasks to be imported on the new project.
Steps to reproduce

   1. Export tasks from a project
   2. Create a new empty project
   3. Import tasks on the new project with default configuration (or with
   "semicolon" separator, in case)

It's the same from an instance to the same instance and from an instance to
another instance (e.g. local to local OR framaboard to local).
Configuration Kanboard

   - Kanboard version: 1.0.40
   - Database type and version: mysql 5.7.14-log
   - PHP version: 7.0.15
   - OS: Linux 3.14.79-grsec-hosting-web-3.14

My computer

   - OS: Windows 8.1
   - Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101
   Firefox/53.0

If I missed some information, please tell me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanboard/kanboard/issues/3107>, or mute the thread

**Comment by fguillot** [comment]
Duplicate to #2951
