### ISSUE TITLE
force password change on first connection

### ISSUE THREAD

**Issue by maggick** [kanboard/kanboard#320]
Hi,

I just reinstall kanboard from scratch directly from the github repository.
I notice that you can change the admin user and that is a great thing.

But is there a way to force the password change when you login for the first time with the admin account ?

**Comment by GitHub-Lover** [comment]
Additional: When admin open an new user, then the admin can choose, if the user should change password at the first login.

Thank you.

**Comment by levlaz** [comment]
I took a stab at this, but after using a couple of different approaches, there was no real clean way that I could see to do this. I think the best solution would be to have a proper "installer", this way in addition to creating users and changing passwords, you could also configure your database the first time that kanboard runs. 

@fguillot What do you think? Is there no "installer" for a reason, or is it simply because its a lower priority issue for you?

**Comment by fguillot** [comment]
The "installer" is a low priority for me. However, I added a new feature in the dev branch to invite people. In this way, new users can choose their own password, there is no need to set a password for them.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
