### ISSUE TITLE
Restricting file-upload size

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3275]
### Actual behaviour

Today I can upload any file to the server from the sidebar – Attach a document

### Expected behaviour

Is it possible to restrict the file size to control the file upload? eg. max 2MB

### Configuration

Application version: 1.0.43
PHP version: 7.0.17
PHP SAPI: litespeed
OS version: Linux 2.6.32-673.26.1.lve1.4.27.el6.x86_64
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by rautamiekka** [comment]
**_Note:_** I can't speak for other than Apache Web Servers, and whether this works right away ain't guaranteed as I've never tried to restrict a website's file upload like you seek.

You have 2 options:
1) Apache main config
2) the `.htaccess` file Kanboard pre-ships

The Apache main config is fastest since it's read once into RAM on daemon boot up and queried first while the `.htaccess` is processed every single time the folder tree is accessed, but the `.htaccess` is far easier to use.

In the Apache config you need to use specific directives to target the Kanboard area, and which ones it depends. Instead, I'll tell how to do it the `.htaccess` way:

Add this line inside the `<IfModule mod_rewrite.c>` block as the last line:
```htaccess
php_value upload_max_filesize 2M
```

**Comment by izno** [comment]
@rautamiekka Thanks for a quick reply... It is an Apache server I'm running, but I can't get the htaccess file to work the way I want!

It is trying to upload the file, but then there is an error after 100%

`Unable to upload files, check the permissions of your data folder.`

I was hoping to be able to achieve this with a user friendly message popping up and warning that the file is too large – before the user is trying to upload it..

...any guidance would be appreciated!

**Comment by rautamiekka** [comment]
^ Most likely a filesystem permission problem, but you should check Apache's error log first. On Debian/Ubuntu when not using virtual hosts it's `/var/log/apache2/error.log`.

**Comment by fguillot** [comment]
The upload file size is defined by your web server config, not Kanboard. There is already an old ticket about that: https://github.com/kanboard/kanboard/issues/2353#issuecomment-228126908

Concerning, the permissions problem, the procedure is already described in the documentation: https://kanboard.net/documentation/installation and https://kanboard.net/documentation/ubuntu-installation
