### ISSUE TITLE
Enhancement - Custom role - view only tasks assigned to user

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#3318]
Hi,

On the custom roles, I'd like to be able to create a new project role whereby a user **can only view tasks which are assigned to them**.

Thanks,
Algy

**Comment by erpnedir** [comment]
This is one of the most requested feature. Definitely needed a lot.

**Comment by Qrizzz** [comment]
One of the main purposes of Kanban is to see all the work of your teammates in one place. Its great to see what everybody is on and how long it will approximately take to finish a task you want to build on. Isn’t your request the exact opposite direction?

A solution would be a project for every person – but I would not recommend that.

**Comment by erpnedir** [comment]
You are correct, but it depends on the person looking at the board!
Generally, boss or managers want to see all peoples task on the board. But they don't want the employees see each other tasks. Also an employee can prefer to see only his tasks to  concentrate on them. If we have this restriction we can give all two parties the view they need.
Because we don't have this feature, currently two of the companies I recommended using kanboard creates projects per user! This is unnecessary in my view. Also it makes the usage of boss harder.
So, my vote is having this restriction possible.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
