### ISSUE TITLE
Users can not be assigned to other group than LDAP-synced during first login

### ISSUE THREAD

**Issue by felixkretschmer** [kanboard/kanboard#3440]
### Actual behaviour

Users are not elevated to higher user role after re-login.

### Expected behaviour

E.g. Manager role is saved at user profile

### Steps to reproduce

use LDAP as Auth Backend.
Refering to #3182 the next problem is, that users always get assigned the same group as during first login. So if I want to elevate a user after a couple of weeks, the role is not saved but reassigns after the users logs out and in again.

### Configuration

Version: 1.0.46
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS Version: Linux 4.4.0-92-generic
Datenbanktreiber: mysql
Datenbank Version: 5.7.19-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by fguillot** [comment]
If you are using LDAP with group sync, the source of truth is LDAP not Kanboard, at each login the LDAP settings will override KB settings.

**Comment by felixkretschmer** [comment]
Well, source of truth works for every other webapp and program with LDAP-based Auth.
Just Kanboard does not apply changed group-memberships to users. So yes it might not be possible to elevate users to managers in Kanboard. But if I add them to the LDAP-group that is configured for Kanboard-Managers they are not granted Manager-rights either.
After this works in other services perfectly, LDAP does not seem to be the problem.
E.g. we are running a wiki with ACLs based on LDAP-groups. A change in group-membership results in different access to the wiki after the next login.

**Comment by cjohnsonuk** [comment]
I'm seeing something that may be similar.  
With my user in the manager or admin ldap group I was not seeing the "new team project" as I could see in my locally authenticated admin user.

I upgraded to 1.1.0 giving me a config of : 
 Application version: 1.1.0
PHP version: 5.6.32
PHP SAPI: apache2handler
OS version: Linux 3.10.0-693.2.2.el7.x86_64
Database driver: mysql
Database version: 10.1.28-MariaDB 

but the problem persisted.

My user is in the ldap group : KanboardProjects_Administrators
My config contains : define('LDAP_GROUP_ADMIN_DN', 'CN=KanboardProjects_Administrators,OU=Projects,OU=Groups,OU=myou,DC=mydept,DC=mydomain,DC=com');
Logged in as the local authenticated Kanboard Admin and changed my role to administrator from user and the user list shows me as administrator
Logged in as me I see that my profile says administrator
Looking in the database I see my role as app-admin
However I don't see the option for a "new team project" which would suggest something knows at this point I'm not admin despite the profile showing otherwise

I log out my ldap user and looking in the database I see my role as app-admin
I log back in again with my ldap user and looking in the database I see my role as app-user and in both my own view of my profile and the local admin list of all users.

My ldap config settings are 👍 



cat config.php | grep -i "ldap_"
 
define('LDAP_AUTH', true);
define('LDAP_SERVER', 'DC01.mydept.mydomain.com');
define('LDAP_PORT', 389);
define('LDAP_SSL_VERIFY', true);
define('LDAP_START_TLS', false);
define('LDAP_USERNAME_CASE_SENSITIVE', false);
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'ldap_user');
define('LDAP_PASSWORD', 'xxxxxxxxxxxxxxxxxxxxxxxxxx');
define('LDAP_USER_BASE_DN', 'DC=mydept,DC=mydomain,DC=COM');
define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s))');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'displayname');
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');
define('LDAP_USER_ATTRIBUTE_PHOTO', 'jpegPhoto');
define('LDAP_USER_ATTRIBUTE_LANGUAGE', 'preferredlanguage');
define('LDAP_USER_CREATION', true);
define('LDAP_GROUP_ADMIN_DN', 'CN=KanboardProjects_Administrators,OU=Projects,OU=Groups,OU=myou,DC=mydept,DC=mydomain,DC=COM');
define('LDAP_GROUP_MANAGER_DN', 'CN=KanboardProjects_Managers,OU=Projects,OU=Groups,OU=myou,DC=mydept,DC=mydomain,DC=COM');
define('LDAP_GROUP_PROVIDER', true);
define('LDAP_GROUP_BASE_DN', 'OU=Projects,OU=Groups,OU=myou,DC=mydept,DC=mydomain,DC=COM');
define('LDAP_GROUP_FILTER', '(&(objectClass=group)(sAMAccountName=%s*))');
define('LDAP_GROUP_USER_FILTER', '(&(objectClass=posixGroup)(memberUid=%s))');
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');

**Comment by cjohnsonuk** [comment]
Update : With debug on it returns this : 
```
[2017-11-24 12:59:09] [debug] BaseDN=OU=Projects,OU=Groups,OU=myou,DC=mydept,DC=mydomain,DC=com
[2017-11-24 12:59:09] [debug] Filter=(&(objectClass=posixGroup)(memberUid=Chris.Johnson))
[2017-11-24 12:59:09] [debug] Attributes=cn
```
But using that filter in softerra ldap browser against my AD returns no groups.  I would need this filter to return the groups
`(&(objectClass=group)(member=CN=Chris.Johnson,OU=MyUserOU,OU=Users,OU=myou,DC=mydept,DC=mydomain,DC=com))`
but this uses distinguished name not sAMAccountName.  So I think it might all be in the config...  I'm just not sure what to change.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
