### ISSUE TITLE
Feature Request: Kanboard Updater

### ISSUE THREAD

**Issue by TheElbenreich** [kanboard/kanboard#3555]
It would be nice to have an in-app-updater to update to a new kanboard version.

How realistic is this feature?

What is your prefered update-method?

**Comment by fguillot** [comment]
From a security point of view, I don't believe that a good idea.

**Comment by zorn-v** [comment]
> From a security point of view, I don't believe that a good idea.

How about allow doing this via `cli` only ?

**Comment by TheElbenreich** [comment]
> From a security point of view, I don't believe that a good idea.
What do you mean? Whats the security constraint?

**Comment by renothing** [comment]
if you want keep update easy, you can use docker version

**Comment by urbalazs** [comment]
Use a cron job for automatic daily update:
0 2 * * * cd /var/www/kanboard;git pull

This will automatically fetch the latest source code from GitHub.

**Comment by fguillot** [comment]
@TheElbenreich @zorn-v Usually you don't want to allow the web server user to be able to write/overwrite/delete application source code files. You allow only what is really necessary. You could even put the source code outside the document root. Otherwise, someone could exploit a security issue in the software and overwrite any part of the application to place a backdoor...

Moreover, allowing the application to update itself from the user interface will raise many problems and edge cases. Package managers, Docker containers and deployment automation systems like Ansible/Puppet/Saltstack are doing a better job.

@urbalazs Updating Kanboard blindly could lead to some issue, especially if you don't read the ChangeLog.
