### ISSUE TITLE
Replying to comment via email and creating new comment.

### ISSUE THREAD

**Issue by cyclinggeorgian** [kanboard/kanboard#3683]
There is very handy feature to send comments to task via email. As it is now replies to that email go to person who send comment with CC to server email.
Is it possible to create a comment by replaying to that email?

**Comment by jamesrascal** [comment]
This doesn't seem too challenging to resolve. From what I can see there would need to be a few things in place in order to make this happen.

We already have the ability to create comments via the API.
We already have the ability to create tasks via EMAIL.

If you are using a sub domain and a catch all for Kanboard (*.@domain) each task in theory could have an email address for the purpose of replying to and updating the task 394@task.domain.com -> Task 394 updates the comments. 

If you are using a single domain you could use the numeric value of the task instead of the project name to add a comment.  website+394@domain.com.

This can be done in a number of ways. It may not fit in the scope of the project and may need to be built as a separate plugin.

**Comment by aljawaid** [comment]
Usage would be a lot faster if we could reply to comments via email.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
