### ISSUE TITLE
ONLY CAN ADD COMENT AND ATTACH A DOCUMENT

### ISSUE THREAD

**Issue by nilats19** [kanboard/kanboard#3690]
Please your help to get a pluggin that let add a new project restriccion with this funcionality "only can add coment and attach a document". 

Really, my problem is that I dont want that a user can edit the task  but I need that the user can coment and attach a document.

Thanks.

**Comment by tallinn-code** [comment]
This is clearly a feature request

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
