### ISSUE TITLE
[Question] Will Kanboard encounter the same fate as Miniflux 1?

### ISSUE THREAD

**Issue by EpocDotFr** [kanboard/kanboard#3695]
The [first major version of Miniflux](https://github.com/miniflux/miniflux-legacy), by the same author of Kanboard, is now considered as obsolete and is no longer maintained.

Will Kanboard encounter the same fate in the near future?

**Comment by lucaspessoapereira** [comment]
Well, some people just want to watch the world burn.

**Comment by fguillot** [comment]
What is your concern? Miniflux is not dead, Kanboard is not dead.

Miniflux 2 has been rewritten in Go. Technologies evolves. Miniflux 1 received very few updates during last years. I maintained this software for almost 5 years and people can use it for free. 

The source code still there, the software still works. Even if I don't maintain the version 1 to focus on the version 2, this is an open source software, anyone can fork the old version. There is even a migration script to upgrade to the version 2.

As of now, no rewrite has begun for Kanboard. I cannot exclude this possibility in the future considering all the advantages that a Go version could bring. However, since Kanboard is more popular, if a rewrite happen, I will not archive the project, pull-requests will continue to be accepted.
