### ISSUE TITLE
backgroung worker hangs with ... StatementHandler.php on line 240

### ISSUE THREAD

**Issue by Abraka** [kanboard/kanboard#3716]
### Actual behaviour
Im using beanstalkd worker and after some time(hours) I get error message "PHP Warning:  Error while sending QUERY packet. PID=2294 in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240"

Activity log stop working, mail sending not works etc.

### Steps to reproduce
bash-4.2$ ./cli worker
PHP Warning:  Error while sending QUERY packet. PID=2294 in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240

### Configuration
- Kanboard version: 1.20
- Database type and version: mysql mariadb 10.1
- PHP version: 7.12
- OS: centos

**Comment by fguillot** [comment]
You should try to check the logs for more information:

- Check the Mariadb logs
- Check the application debug logs

**Comment by Abraka** [comment]
PHP Warning:  PDOStatement::execute(): MySQL server has gone away in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240
PHP Warning:  PDOStatement::execute(): Error reading result set's header in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240

debug log: lot of - [error] Kanboard\Core\Queue\JobHandler::executeJob: Error during job execution: SQL error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Mysql server is running perfectly OK, any and all other apps using this sql server hasnt any problem.
I already tryed another mysql with default settings which comes fron installations and still same problem with background worker. Looks like youv got a error somewhere in code...or mysql need really some very special settings in order to work with this scenario.

**Comment by filhocf** [comment]
I have a similar situation, whitout a msg error or in Kanboard, Worker or MySQL (5.7), but yes in Beanstalkd: 
```
beanstalkd: prot.c:710 in check_err: read(): Connection reset by peer
```
How I have my env over docker, one container per service, i.g., one for each: mysql, kanboard, worker and beanstalkd, all over a swarm, I stop the worker container and swarm restart it, so worker take a look in beanstalkd and process all its queue.

**Comment by claywhitehurst** [comment]
I've had the same issue for the last several releases, dating back to at least the 1.0.x series.  It happens every morning during the daily cronjob.  I'm running it on PHP 5.6 and MySQL 5.6, with supervisord and RabbitMQ instead of beanstalkd.

The only thing that shows up in the Kanboard worker log is

```PHP Warning:  Error while sending QUERY packet. PID=17640 in /var/www/vhosts/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240```

With debugging turned on, all of the SQL looks okay with no errors and no long query times or unusual memory usage.  Then when it's attempting to post overdue tasks to Slack, the debug log shows

```[2018-06-08 08:30:07] [error] Kanboard\Core\Queue\JobHandler::executeJob: Error during job execution: SQL Error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away```

After that happens, the application works fine but it won't post to Slack at all until the worker is restarted.  There are no errors in the MySQL logs and no other users of that MySQL instance are affected.  Also, at least one time I restarted the worker a few minutes _before_ the daily cron job and it ran with no errors.

### Configuration
- Kanboard version: 1.2.4
- Database type and version: MySQL 5.6
- PHP version: 5.6
- OS: Ubuntu
- Background jobs: RabbitMQ

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.8/developer_guide/faq.html).
