### ISSUE TITLE
Fast task adding [Feature Request]

### ISSUE THREAD

**Issue by jonorozcoc** [kanboard/kanboard#3738]
Currently Kanboard opens a modal where you put all task's information. I could be more efficient if we can add tasks just adding the title like Trello and then organize all the respecting info.

![image](https://user-images.githubusercontent.com/8442497/36646019-cd931244-1a3f-11e8-851a-96093c3a2cbf.png)

After that if you create a new task the input is kept to create a new one and so on.

**Comment by matteomazza91** [comment]
Maybe I misunderstood because I don't know this Trello feature. 
How this feature is different from the "Create tasks in bulk"?
![image](https://user-images.githubusercontent.com/27355549/47841875-47525100-ddbb-11e8-89b2-f25b98d843fc.png)

![image](https://user-images.githubusercontent.com/27355549/47841912-6c46c400-ddbb-11e8-83db-3edbf5decff0.png)

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
