### ISSUE TITLE
reopen  #2815 Create a Task for a Group  (please)

### ISSUE THREAD

**Issue by isAAAc** [kanboard/kanboard#3771]
request  #2815 ( Create a Task for a Group ) has been closed by the bot, 
but this feature is still requested, 
reopen it please

**Comment by fguillot** [comment]
This is not going to happen magically. If you need something that nobody else is willing to develop, you should consider contributing to the project.

**Comment by fguillot** [comment]
This feature request was open for 2 years. People rarely develop huge feature requests during their spare time. More details about this in the FAQ: https://docs.kanboard.org/en/latest/developer_guide/faq.html

**Comment by isAAAc** [comment]
Yes two years we're waiting someone to dev it :/

**Comment by creecros** [comment]
I took a look at it, if it makes you feel better...I couldn’t figure out an easy way to do it, and don’t need a feature like this, so stopped looking into it. I’m a shitty coder though, so there’s that.

**Comment by isAAAc** [comment]
thx a lot @creecros , we can build groups in kanboard, can't we assign a task easily to one of those groups ?

**Comment by creecros** [comment]
Not easily, that I could find. The task table only has owner_id for assignment, and everything related is based on looking up that user id. Would need a way to determine  that a group was assigned, instead of a user, and then a way to iterate through each user in the group, to perform whatever function that relates to assignment. There is probably a simple way to do it, but I usually don't find simple solutions until I go through complicated ones. I design and manufacture health and beauty products...so I am clearly not a programmer by trade, but I will continue to look at it with no promises.

**Comment by isAAAc** [comment]
thx a lot for your help && engagement ;)

**Comment by creecros** [comment]
Started working this, I think adding the functionality might be doable for an amateur such as myself, in the form of a plugin. I “should” be able to add the option in task creation and modification to assign a group, then display the assign group in task details and the board view, allow filtering and dashboard query. However, it will be an added field in the task table, thus actions such as automatic actions, aka plugins, would have to utilize it independently. So, for example, an automatic email to Assignee, will email only to assigned user unless the plugin author rewrites their plugin to utilize the new field. Make sense?

**Comment by creecros** [comment]
For reference and collaboration, https://github.com/creecros/group_assign

I welcome any help or support in development.

**Comment by creecros** [comment]
Done. Enjoy.

**Comment by fguillot** [comment]
You can now use the plugin of @creecros if you need this feature.
