### ISSUE TITLE
TimeTrackingEditor plugin should be removed from the list of plugins

### ISSUE THREAD

**Issue by neiaberau** [kanboard/kanboard#3783]
TimeTrackingEditor plugin should be removed from the list of plugins, it currently does no longer work, it produces the error: Internal Error: Identifier "sessionStorage" is not defined.

I assume this is due to SessionStorage.php no longer exists in the source code

**Comment by fguillot** [comment]
This plugin is marked to be compatible only with Kanboard 1.0.38 https://github.com/kanboard/website/blob/master/plugins.json#L612

Looks like the author is going to update his plugin: https://github.com/stinnux/kanboard-Timetrackingeditor/issues/22#issuecomment-375221480

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
