### ISSUE TITLE
Complexity float

### ISSUE THREAD

**Issue by rafacamargo123** [kanboard/kanboard#3790]
We've made a change on kanboard to use in our organization, to accept float values in the "score/complexity" field.  We have "?.5" complexities.
In order to acomplish that, we had to change several files (including all translation files -- the key 'New complexity: %d') and the table task schema.
Is it interesting for you that we make a pull request with all those changes?
If so, what's the rule to database changes, how to we put them into the code?
Thank you

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
