### ISSUE TITLE
Invite People Email Subject..

### ISSUE THREAD

**Issue by saleheenkhan** [kanboard/kanboard#3792]
This software focus on simplicity, the number of features is voluntary limited.

we want email subject to have a different name . Can anybody help me on that?

Thanks

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
You should ask questions on the [forum](https://github.com/kanboard/forum/issues). This place is reserved for bug reports.

To change the subject, you have to modify the source code by yourself. Take a look here: https://github.com/kanboard/kanboard/blob/master/app/Model/InviteModel.php#L55

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
