### ISSUE TITLE
Merging users

### ISSUE THREAD

**Issue by GillesMoyse** [kanboard/kanboard#3795]
### Actual behaviour
Some users lose their ids, so they create a new user and start working with it. A few days later, they have 2 users with several tasks assigned to each.

### Expected behaviour
How can I merge the two accounts? I'd like to transfer all the tasks from one user to the other.

**Comment by fguillot** [comment]
There is no notion of "merging users". The behavior that you described depends on how you configured the application on your own server and how you use it.

Please, use the forum for that kind of questions.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
