### ISSUE TITLE
Integrate image in the post

### ISSUE THREAD

**Issue by villamagnadiego** [kanboard/kanboard#3796]
Hi all, 
do you know if is possible to identify a single card by an image instead of a text?

Thank you
Diego

**Comment by Qrizzz** [comment]
Maybe the [Plugin Coverimage](https://github.com/BlueTeck/kanboard_plugin_coverimage) fits your needs?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
