### ISSUE TITLE
Make Description icon Bigger AND Red with text "View Details"

### ISSUE THREAD

**Issue by fixpix45** [kanboard/kanboard#3798]
This issue is:

[] Improvement
Make Description icon Bigger AND Red with text "View Details"
See feature request: https://github.com/kanboard/kanboard/issues/2468 

This addresses the issue where people complain that the description is not visible when in fact it just hard to see.

To implement go to Settings > Application settings
Add the following text to the Custom CSS text box:

.fa-file-text-o::before {
color: #f00;
font-size: 20px;
font-weight: bolder;
content: "\f0f6  View Details";
}

![image](https://user-images.githubusercontent.com/37987154/38177986-d3262450-35bd-11e8-8b5d-7607c5ecbd87.png)

**Comment by fguillot** [comment]
You should post custom css examples on the [forum](https://github.com/kanboard/forum/issues). This issue tracker is reserved for bug reports.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
