### ISSUE TITLE
Excel Attachment - File Corrupted

### ISSUE THREAD

**Issue by Inspop-Design** [kanboard/kanboard#3801]
Hi,
As we migrated to new version, we see that any excel attachment on a task doesn't opens. 

Steps
====
a.) Create a task
b.) Attach a excel file with .xls or .xlxs
c.) Download the file from task.
d.) It renders below error : 
http://take.ms/Fl9Kd
e.) As we open the file...entire file is corrupted.
http://take.ms/jm85b
f.) Tried multiple excel files (files were perfectly opening before uploading to kanboard). The moment you download and open downloaded file this issue comes.
g.) Tried word file as well. Same issue is shown (file corrupted). However opening the corrupted file works fine for word but not for excel.

Hope i explain the issue  properly.

**Comment by Inspop-Design** [comment]
As you upload something into Kanboard, the file format is changed and stored inside \data\files\tasks  . This format isn't something which can be opened directly - http://take.ms/0uDy3

There shalln't be any firewall issue as before migration, older version used to work perfectly with all attached files opening.

**Comment by Qrizzz** [comment]
Can you try downloading the file, add the extension (`.xls` in your example) and open it? This works in my environment. 

Perhaps the problem is due to some read/write limitations?

**Comment by fguillot** [comment]
I believe this is related to the other issue that you opened before: #3776

Kanboard doesn't alter the file itself. When you upload an attachment, the file is just moved to the data folder with a unique name.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
