### ISSUE TITLE
DemoData plugin released

### ISSUE THREAD

**Issue by bdeshayes** [kanboard/kanboard#3802]
Just released
https://github.com/bdeshayes/Kanboard-plugin-DemoData

May it be listed at
https://kanboard.org/#plugins

**Comment by fguillot** [comment]
The instructions to add your plugin are here: https://github.com/kanboard/website#how-to-add-a-new-plugin-to-the-list

**Comment by bdeshayes** [comment]
Updated the files plugins.json and index.html, then sent a pull-request.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
