### ISSUE TITLE
Migration 128 : Duplicate column name 'filter'

### ISSUE THREAD

**Issue by oloynet** [kanboard/kanboard#3803]
[] Bug report

### Actual behaviour

When installing a fresh new install from the master, the migration 128 made an error
**Duplicate column name 'filter'**

### Steps to reproduce

After installing and configuring for MySQL

    php cli

    Unable to run SQL migrations: Running migration \Schema\version_128, SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'filter' (You may have to fix it manually)

### What I've made for working

I desactivate the code inside app/Schema/Mysql.php :

    function version_128(PDO $pdo)
    {
        //$pdo->exec('ALTER TABLE `users` ADD COLUMN `filter` VARCHAR(255) DEFAULT NULL');
    }

### Logs

Unable to run SQL migrations: Running migration \Schema\version_128, SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'filter' (You may have to fix it manually)

### Configuration

- Kanboard version: master from GIT
- Database type and version: MySql 5.7.21-0ubuntu0.16.04.1 (Ubuntu)
- PHP version: PHP 7.0.28-1+ubuntu16.04.1+deb.sury.org+1 cgi-fcgi
- OS: Ubuntu16.04.1 - Linux 4.4.0-116-generic
- Browser:Chrome/59.0.3071.115 Safari/537.36

**Comment by fguillot** [comment]
This behavior could happen if multiple process are altering the database schema in the same time.

More details here:
- https://docs.kanboard.org/en/latest/admin_guide/upgrade.html#running-sql-migrations-manually
- https://docs.kanboard.org/en/latest/admin_guide/faq.html#solving-database-migration-issues

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
