### ISSUE TITLE
"Daily background job for tasks" only with plugin?

### ISSUE THREAD

**Issue by sthesing** [kanboard/kanboard#3807]
This issue is:

A Question do I need a plugin like Beanstalk in order to use automatic actions using the event "Daily background job for tasks"? Or should they work without such a plugin (e.g. using cron)?

**Comment by fguillot** [comment]
You just need to configure the cronjob. See https://docs.kanboard.org/en/latest/admin_guide/cronjob.html

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
