### ISSUE TITLE
[Feature Request] GitBucket Integration

### ISSUE THREAD

**Issue by frontbear** [kanboard/kanboard#3816]
This issue is:

- [ ] Bug report
- [x] Feature request
- [ ] Improvement

I do most of my work on self-hosted GitBucket ( https://gitbucket.github.io/ ), it would be great to have the same integration as Github/Gitlab/BitBucket.

Thanks!

**Comment by lastlink** [comment]
most of the other integrations are plugins, I think if you really want support just build out your own plugin for this. I don't think there are lot of users using this. Since there are 3 different plugins each for Github/Gitlab/BitBucket it should be easier to setup. The key thing is gitbucket oauth support &/or there rest api.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
