### ISSUE TITLE
performance drastically deteriorates as task quantity increases

### ISSUE THREAD

**Issue by ChangePlaces** [kanboard/kanboard#3822]
This issue is:

- [x] Bug report

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Actual behaviour
As the number of tasks in a project grows, releasing after dragging a task around causes the board to become unusable with the spinner showing in the bottom right corner as well as the task being greyed out. As more tasks are present, the delay increases. In one project I have over 500 open tasks, and I'm up to around 3-4 seconds delay just after dragging a task.

This is with SQLite database, with approx 2000 tasks across all projects (mostly all closed).

### Expected behaviour
No noticeable delay after dragging and releasing a task.

### Steps to reproduce
- add approximately 500 tasks to a project
- drag a task from one col to another

- could this be from something as simple as a missing index on the db? I suspect this is the case due to the performance decreasing as row count increases.

### Configuration

- Kanboard version: 1.2.2
- Database type and version: Sqlite 3.11.0
- PHP version: 7.1
- Browser: browser independent

**Comment by dhornford** [comment]
We also experience the same delay.
Our server (AWS micro linux & AWS RDS Mysql) won’t indicate above 5% CPU
with load <0.04. Network traffic is light.
We suspect it is in the sequence of drawing the board. I have not figured
out how to use one of the web-site performance tools to see the complete
set of requests to draw the board.
When column is hidden it will briefly flash open and be redrawn closed.

Te server simultaneously provides a few other web-based systems and
experiments show they remain very responsive
Experiments were hunting transitory network issues, and whatever to see if
we could isolate a problem in our world.

Dave
-- 
Dave Hornford
Conexiam. Straightforward answers to complex problems.
Canada +1.403.818.4303 Mobile  +1.916.695.3859

On April 17, 2018 at 6:27:32 PM, ChangePlaces (notifications@github.com)
wrote:

This issue is:

   -

   Bug report
   -

   Please, read the Frequently Asked Questions
   <https://docs.kanboard.org/en/latest/developer_guide/faq.html>.
   -

   Ask questions on the Forum <https://github.com/kanboard/forum/issues>.

Actual behaviour

As the number of tasks in a project grows, releasing after dragging a task
around causes the board to become unusable with the spinner showing in the
bottom right corner as well as the task being greyed out. As more tasks are
present, the delay increases. In one project I have over 500 tasks, and I'm
up to around 3-4 seconds delay.

This is with SQLite database, with approx 2000 tasks across all projects
(mostly all closed)
Expected behaviour

No noticeable delay after dragging and releasing a task.
Steps to reproduce

   - add approximately 500 tasks to a project
   - drag a task from one col to another

Configuration

   - Kanboard version: 1.2.2
   - Database type and version: Sqlite 3.11.0
   - PHP version: 7.1
   - Browser: browser independent

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanboard/kanboard/issues/3822>, or mute the thread

**Comment by ChangePlaces** [comment]
Interesting, I wonder if, when a swimlane / col is hidden, if the tasks can not be loaded into, or removed from the DOM?

**Comment by fguillot** [comment]
This issue has been discussed here in the past: https://github.com/kanboard/kanboard/issues/3297#issuecomment-338335879

There are a lot of room for improvements:

- Rethink how the board is rendered
- Rethink how the task position are updated in the database
- All operations that generate long I/O are executed synchronously: sending an email, a notifications (there is an optional background worker but it's a hackish solution because PHP...)

All these things are inefficient and slow. In addition to that, technologies used are almost considered legacy nowadays (PHP/jQuery).

**Comment by ChangePlaces** [comment]
well. some interesting points in the comments. i'd be for just returning a basic ajax response, including success. column task counts can be implemented client side, and would only need to be wrapped in some spans which jquery could target each of on a task drop event. the task count could be stored in a js var, or just counted dynamically. even the least efficient last option there is going to be heaps faster than returning the whole page.

as for automatic actions, isn't the page updated every x seconds anyway? as user defined.

**Comment by Abraka** [comment]
**technologies used are almost considered legacy nowadays (PHP/jQuery)** ...fguillot what do you mean by that? Do you plan to rewrite kanboard with ruby or python or something else?

**Comment by amff1704** [comment]
I had the same problem coming with the increasing number of users/tasks/projects. Now, after I’ve migrated to Mysql, no problem at all. All goes as smoothly as it can be. I have around 30+ projects with more than 300 tasks each and all with couverimages and files associated.

Chears

**Comment by ChangePlaces** [comment]
@amff1704 Interesting - was this from a sqlite database as well?

**Comment by lastlink** [comment]
Would it not be possible to make changes to the ui w/out rerendering the page?

**Comment by amff1704** [comment]
@ChangePlaces Yes, I was comming from a sqlite db.

**Comment by amff1704** [comment]
@jack1729  I'm on a recent machine, with SSD, xeon (etc) with Linux server 16.04, I did a clean regular MySQL, from the linux repository, install. I had no problems so far, over 60 projects, 20 to 300 tasks each by now...

**Comment by lastlink** [comment]
Probably b/c you have way more hardware and resources dedicated for it that most of us running on shared web hosts.

**Comment by lastlink** [comment]
Is this still an issue? Seems that there were recent improvements to this with the compact view vs expanded. I noticed that you can drag individual tasks and it will attempt to change each one w/out doing a page refresh. The popup task edit modal is still slow though.

**Comment by fguillot** [comment]
Please continue the discussions on the [forum](https://kanboard.discourse.group/) as there are so many ways to improve the performances of the application.
