### ISSUE TITLE
add new metadata to tasks

### ISSUE THREAD

**Issue by dino124** [kanboard/kanboard#3865]
Hello, please walk me through how to add tasks metadata like category for example. There are couple fields I need to display in the task form?
Thanks a lot.

**Comment by ltajariolli** [comment]
That would be useful

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
