### ISSUE TITLE
Project ID is not properly filtered

### ISSUE THREAD

**Issue by grayed** [kanboard/kanboard#3982]
### Actual behaviour

Let we have two projects: with numeric IDs 1 and 2. The project 1 has tasks 1 and project 2 has task 2. Now, if we try to access task 2 via URI (either rewritten or not) with different project ID we get the following results (host part is ommitted):

- /kanboard/project/2/task/2 — the task is shown, OK
- /kanboard/project/1/task/2 — access is denied, OK
- /kanboard/project/MOO/task/2 — the task is shown, BUG

Actually, any non-integer value there, including empty string, results in task being shown.

I'd expect either:

- invalid project numeric ID cause deny of access;
- project ID always ignored;
- (preferred) same as (a) but allow actual project ID used instead of numeric one be used.

The latter variant may help to fix another issue, with task IDs being database-wide, not project-wide. I.e., you can't have, say, task 34 in two different projects, and thus if you duplicate project, or import-restore it, you'll run into problems if you have those tasks referenced somewhere (e.g., in commit messages).

### Steps to reproduce

Take any task URI and change projectid field there to a nonsense.

### Configuration

- Kanboard version: 1.2.5
- Database type and version: SQLite 3.22.0
- PHP version: 7.0.28
- OS: OpenBSD 6.3/amd64
- Browser: Chromium 68.0.3446.106

**Comment by Abraka** [comment]
Thx for heads UP. This is serious security hole.

**Comment by grayed** [comment]
Any ideas about what/where needs to be touched to make this issue fixed? It's still in 1.2.6. :(

**Comment by rafacamargo123** [comment]
I don’t think this is a security hole because I could only reproduce for projects I’m a member OR for every project when the user is an application admin, hence has access to all of the projects even not being a member of them. When an admin user is not a member of a project, they just don’t appear as a possible assignee on tasks opened on that projects nor the projects appears on projects selector for them, but as admin they can still see project management and manage every project. 
I tested this with a user with a role Manager and User and I could not open tasks from projects I’m not a member.

**Comment by rafacamargo123** [comment]
For document purpose, the commit that included that "if": https://github.com/kanboard/kanboard/commit/2d5621af2f3678ce4959a450663f5657098144bc
