### ISSUE TITLE
Matrix plugin removed from Kanboard?

### ISSUE THREAD

**Issue by andrewshadura** [kanboard/kanboard#3992]
Hi,

I’ve just noticed the plugin disappeared from the kanboard project without any prior notice, was there any issue with it? Can it be reinstated?

Thanks!

**Comment by fguillot** [comment]
Your plugin still there: https://github.com/andrewshadura/kanboard-plugin-matrix

If you are talking about the issue #3448, yes I removed the fork because I'm not the maintainer. Since your are the author of the plugin, this is better to keep the original repo where is it and have a reference on the website like other plugins: https://github.com/kanboard/website#how-to-add-a-new-plugin-to-the-list

**Comment by andrewshadura** [comment]
Hmm. The reason I opened #3448 was because I wanted the Matrix.org plugin to become part of the Kanboard project, and not be an external thing. If it's about you being the maintainer, I’m fine with it, the plugin doesn’t require much maintenance anyway (the Matrix API hasn’t changed since then).

**Comment by andrewshadura** [comment]
Actually, I did explain the reason in the original issue.
