### ISSUE TITLE
Error in Public display of Task - Illegal string offset 'name

### ISSUE THREAD

**Issue by RPitch** [kanboard/kanboard#4060]
Warning: Illegal string offset 'name' in /home/[blah]l/Kanban/app/Template/task/details.php on line 159

snippet for Line 159 in details.php contains  
 <?php foreach ($tags as $tag): ?>
                        <li class="task-tag <?= $tag['color_id'] ? "color-{$tag['color_id']}" : '' ?>"><?= $this->text->e($tag['name']) ?></li>
                    <?php endforeach ?>

Why is $tag['name'] returning the error - nb the rendered page shows the first letter of 'name' ??

**Comment by Cyboulette** [comment]
Hello,

I have the same problem and I'have fixed that (I will submit a PR or if someone want to do it).

in **app/Controller/TaskViewController.php** find these lines
```php
'tags' => $this->taskTagModel->getList($task['id']), // Line 48

'tags' => $this->taskTagModel->getList($task['id']), // Line 96
```

in **app/Controller/ActivityController.php** find this line
```php
'tags'    => $this->taskTagModel->getList($task['id']), // Line 59
```

Replace all these lines in these files by this line : 
```php
'tags' => $this->taskTagModel->getTagsByTask($task['id']),
```

In fact taskTagModel->getList() is used in the Edit Form in order to display tags but in views, task have color, name and ID, and it's needed to call taskTagModel->getTagsByTask($idOfTheTask) instead :) 

I'm not sure this is the best solution, but this method is used in the function show() of Task.

Hope this solution will help :)

**Comment by RPitch** [comment]
Yep That did the trick - thanks #Cyboulette!

*Ray Pitch*

**Comment by k10blogger** [comment]
I was facing problems in transitions, timetracking, analytics, show.
So i updated the above in all of those function in the TaskViewController.php

So thanks for this information.
