### ISSUE TITLE
Don't show two task counts per column when there is only one swimlane

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#4208]
For the simple case where a board has only one swimlane, instead of showing this in the column headers:

 + (5) In progress (5)

...you should simplify and save some precious horizontal space by simply showing it as:

 + In progress (5)

**Comment by creecros** [comment]
Best suited for forum and I believe I did something like this already. 
https://kanboard.discourse.group/t/feature-request-option-to-disable-swimlane-features/49

https://github.com/creecros/oneswimlanetorulethemall

**Comment by nekohayo** [comment]
In this case here I think it's kind of a user experience "bug" rather than feature request, in the sense that the software should automatically do the "right" thing by default; no point in showing two sets of numbers if there is only one swimlane.

Furthermore, in the case where there _are_ multiple swimlanes, the visual presentation with the two numbers being on opposite ends is still not only space-inefficient, it is a bit confusing. Instead of, for example, "(3) In progress (5)" I would recommend something like "In progress (3/5)", it would look a bit cleaner.

**Comment by rafacamargo123** [comment]
> "In progress (3/5)"

Something like that is already used when you put a limit to a column (Project settings > columns > edit a column > set a Task Limit.

Full format today:

![image](https://user-images.githubusercontent.com/12586009/59736801-737aef00-9231-11e9-8861-305f39466598.png)

I agree it's a little confusing.

- The gray numbers can't go away because of the task limit by columns
- The "score sum across all swimlanes" only is shown when there are more than one swimlane active

So, I think the best solution is to hide the first number, the one before the column title, when there is only one swimlane. The first gray number (count across all swimlanes) is always shown.

**Comment by creecros** [comment]
A user with a big big big name...

**Comment by rafacamargo123** [comment]
It was a test from another issue 😬
