### ISSUE TITLE
Space savings: subtasks table's first column should have flexible width

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#4213]
Tested with the latest stable version (the bug has been around forever howeve), this is what I typically get in the UI:

![kanboard subtask table columns default sizing](https://user-images.githubusercontent.com/479401/59314313-c6c5ce00-8c82-11e9-807a-a3f1929b2d05.png)

This leads to the subtask titles wrapping around in a pretty inelegant way, while the third (time spent / stopwatch) column is full of unused space.

Looking at the HTML code, the table's first "th" element is `<th class="column-45">Title</th>`, the second is `<th class="column-15">Assignee</th>` and the third is just `<th>Time tracking</th>`.

The fix appears to be simple then: remove the class from the first th, and put `class="column-15"` onto the third th. And this is the result:

![kanboard subtask table columns proposed sizing](https://user-images.githubusercontent.com/479401/59314405-35a32700-8c83-11e9-9e3a-6693512e6004.png)

**Comment by rafacamargo123** [comment]
Actually the third column cannot have a small size because the time spent and time estimated of subtasks:

![image](https://user-images.githubusercontent.com/12586009/59735064-69092700-922a-11e9-9c14-9ed1cc1fa2c5.png)

**Comment by rafacamargo123** [comment]
@nekohayo In settings > Application settings > Custom stylesheets you can add the following css to make your kanboard show this table with default html table behaviour (biggest content, biggest cell):
```css
table.subtasks-table th {
  width: initial !important;
} 
```

Results:

![image](https://user-images.githubusercontent.com/12586009/59735422-e41f0d00-922b-11e9-83f3-93828568535c.png)

![image](https://user-images.githubusercontent.com/12586009/59735437-f305bf80-922b-11e9-8b1b-f54d2adc93b3.png)

![image](https://user-images.githubusercontent.com/12586009/59735457-031d9f00-922c-11e9-80a1-1c1a7d3af06b.png)

**Comment by rafacamargo123** [comment]
I've changed the code, removing the classes from all `<th>`s , but I did not like the result.
See, the subtasks and links tables are "pretty", having columns the same size:

![image](https://user-images.githubusercontent.com/12586009/59736047-7aecc900-922e-11e9-8335-7a50b8e3e76a.png)

Appling this solution I suggested you will make a "mess":

![image](https://user-images.githubusercontent.com/12586009/59736116-acfe2b00-922e-11e9-8610-d4b5549728e7.png)

However, i'm not the owner of this repository. I will not suggest this change but can't deny it either.

**Comment by nekohayo** [comment]
I would say that triple-digits hours spent on a subtask are a corner case; if you spent over a 100h (that's nearly 3 weeks of fulltime work, folks) on a subtask, is it really a "sub"task? ;) much more likely that it will be single or double-digit. And when it gets to triple digit, I consider that it should remove the decimals (".00") from the display (but not the data itself) to save space because that level of precision/significance is meaningless when you're dealing with such big numbers, so then you can save 2x3 = 6 characters. The "/ number estimated" could also be replaced by " (number estimated)" for clarity and to save one extra character, but that's micro-optimization at that point.

Personally I care much more about the task names not wrapping in an ugly way 90% of the time, than the time tracking column possibly wrapping 10% of the time.

Anyway I think my initial fix proposal (swapping around the 1st and 3rd column's width) was a reasonable "symptom fix", and if it's not considered reasonable then there is still a "hard bug" of "the wrapping looks like crap because it wraps below the icons instead of aligning with the 1st text line", and that remaining "root cause" is tougher to fix than giving enough space for the problem to "not occur most of the time"...

**Comment by SladeP** [comment]
@nekohayo  

So, I did some tinkering with the formatting of subtasks to make them more readable and space-conscious. I've included some screenshots to display the before and after. Please let me know what you think.

First, a couple of notes on why I did what I did:

* I set the time tracking column to column-30 because that's the smallest size that will accomodate all languages (Spanish being the longest, so I included a screenshot of it.)

* I made the time tracking column next wrap in mobile because we don't need this huge long line for scrolling in mobile, it's readable enough when wrapped (screenshot included)

* I grouped the move icon and settings icon and checkbox into flex containers so text would wrap under itself, not under those icons. This makes wrapping look cleaner and easier to read.

I have stored these changes in the [branch fix-4213 in my fork of Kanboard.](https://github.com/SladeP/kanboard/tree/fix-4213) You can clone it and take a look for yourself if you want.

Now, screenshots:

# My Subtasks Before

![mysubtasks_before](https://user-images.githubusercontent.com/25444175/69275428-966f4d80-0b99-11ea-8c7c-43e7a891b704.png)

![mysubtasks_mobile_before](https://user-images.githubusercontent.com/25444175/69275460-a850f080-0b99-11ea-8dce-36125e3ad563.png)


# My Subtasks After

![mysubtasks_after](https://user-images.githubusercontent.com/25444175/69275441-9cfdc500-0b99-11ea-9246-9c04a3c57b04.png)

![mysubtasks_mobile_after](https://user-images.githubusercontent.com/25444175/69275478-aedf6800-0b99-11ea-839d-ee4aaaec7d16.png)



# Tasklist Before

![tasklist_before](https://user-images.githubusercontent.com/25444175/69275512-c7e81900-0b99-11ea-8302-3ae54afb2aab.png)

![tasklist_mobile_before](https://user-images.githubusercontent.com/25444175/69275596-ef3ee600-0b99-11ea-866e-9a38b925713a.png)


# Tasklist After

![tasklist_after](https://user-images.githubusercontent.com/25444175/69275517-cae30980-0b99-11ea-97c4-eed865ab6b3b.png)

![tasklist_mobile_after](https://user-images.githubusercontent.com/25444175/69275585-eb12c880-0b99-11ea-8796-d7866bb0dc09.png)



# Task View Before

![taskview_before](https://user-images.githubusercontent.com/25444175/69275662-11d0ff00-0b9a-11ea-85a7-ee3cdadf6aab.png)

![taskview_mobile_before1](https://user-images.githubusercontent.com/25444175/69275783-4cd33280-0b9a-11ea-9c06-6dfd35bcd945.png)

![taskview_mobile_before2](https://user-images.githubusercontent.com/25444175/69275796-5361aa00-0b9a-11ea-84bf-fb6acbad67ea.png)

![taskview_mobile_before3](https://user-images.githubusercontent.com/25444175/69275802-578dc780-0b9a-11ea-98fa-d6983455fb61.png)


# Task View After

![taskview_after](https://user-images.githubusercontent.com/25444175/69275668-14335900-0b9a-11ea-92d5-106021f60995.png)

![taskview_mobile_after1](https://user-images.githubusercontent.com/25444175/69275700-2614fc00-0b9a-11ea-948f-7680ca8e01f1.png)

![taskview_mobile_after2](https://user-images.githubusercontent.com/25444175/69275716-2d3c0a00-0b9a-11ea-83f2-14e7fc7cf7dc.png)

![taskview_mobile_after3](https://user-images.githubusercontent.com/25444175/69275721-3036fa80-0b9a-11ea-8234-40695d54944e.png)



# Task View Spanish Before

![taskview_spanish_before](https://user-images.githubusercontent.com/25444175/69275763-42189d80-0b9a-11ea-918e-3da3a34183e7.png)


# Task View Spanish After

![taskview_spanish_after](https://user-images.githubusercontent.com/25444175/69275759-3fb64380-0b9a-11ea-8828-35767a9d7a16.png)
