### ISSUE TITLE
Bad translation on Date Picker (spanish)

### ISSUE THREAD

**Issue by consultorml** [kanboard/kanboard#4335]
### Actual behaviour

When select start date or due date, the date picker have mixed translations on chinese (or similar language) and english. 

### Expected behaviour

Date picker with all translations on spanish. In version 1.2.11, the translation works. 

### Steps to reproduce
Change the language to Español (España) or Español (Venezuela)

### Screenshots

![datepicker](https://user-images.githubusercontent.com/57487761/68530617-8da09100-02e8-11ea-9d66-86ca54cbd6cf.png)

### Configuration

    Kanboard version: 1.2.12
    Database type and version:  10.1.41-MariaDB
    PHP version: 7.2.24
    OS: Ubuntu 18.04
    Browser: Chrome / Firefox

**Comment by SladeP** [comment]
@consultorml the fix for this was merged into master and should now be good to close!

**Comment by consultorml** [comment]
Thank you @SladeP.  I made the changes and works flawlessly.

**Comment by orware** [comment]
Good morning,

I'm just upgrading to the current release (1.2.13) and am experiencing this issue as well (same Chinese text as shown in the screenshot above), although we have the default language set to English and I can see that the files installed on the server reflect the new change that was merged in with #4347. 

Not sure if there's any PHP caching occurring of the previous files, which could potentially be a source of the issue somehow, but I don't think that's the issue here (I've already completed a few actions that should rule that out as the potential source of the issue on my end).

**Comment by orware** [comment]
For my issue it seems like it might be related to the Customizer plugin so I've reported that separately over here: https://github.com/creecros/Customizer/issues/103

This issue may be able to remain closed since it doesn't seem to be due to the main Kanboard code anymore.
