### ISSUE TITLE
Kanboard permission denied on data dir

### ISSUE THREAD

**Issue by 2tata** [kanboard/kanboard#4367]
### Actual behaviour
After rebooting my laptop I was not able to assess kanboard again. I am getting following error message: `Internal Error: The directory "/usr/share/nginx/html/kanboard/app/../data" must be writeable by your web server user`

This behavior is similar to Issue: #2397

### Expected behaviour
Some nice GUI with plenty of colure full tasks.

### Logs
I haven't found anything in the log files.

### Configuration

- Kanboard version: Version 1.0.40 (Feb 24 2017)
- Database type and version: NA
- PHP version: PHP 7.4.0 (fpm-fcgi)
- OS: 5.4.1-arch1-1 #1 SMP PREEMPT
- Browser: Firefox 71.0 (64-bit)

nginx.conf:

```
worker_processes  1;

events {
	worker_connections  1024;
}

http {
	include             mime.types;
	default_type        application/octet-stream;
	sendfile            on;
	keepalive_timeout   65;
	types_hash_max_size 4096;

	# Example configuration for a dedicated kanboard site
	server {
		listen      127.0.0.1:80;
		server_name kanban.local;
		root        /usr/share/nginx/html/kanboard;
		index       index.php index.html;

		location / {
			try_files $uri $uri/ /index.php$is_args$args;
			# If Kanboard is under a subfolder
			# try_files $uri $uri/ /kanboard/index.php;
		}

		location ~ \.php$ {
			try_files $uri =404;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_index index.php;
			include fastcgi_params;
		}

# Deny access to the directory data
		location ~* /data {
			deny all;
			return 404;
		}

# Deny access to .htaccess
		location ~ /\.ht {
			deny all;
			return 404;
		}
	}
}
```

nginx -t
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

```

ps -ef | grep '[h]ttp'
```
http         864     852  0 09:42 ?        00:00:00 php-fpm: pool www
http         865     852  0 09:42 ?        00:00:00 php-fpm: pool www
tata        2780    1226  0 11:13 ?        00:00:00 /usr/lib/gvfsd-http --spawner :1.5 /org/gtk/gvfs/exec_spaw/1
http        3254     858  0 11:24 ?        00:00:00 nginx: worker process
```

```
/usr/share/nginx/html/kanboard/data
├── [http     http    ]  db.sqlite
├── [http     http    ]  files
│   └── [http     http    ]  tasks
│       └── [http     http    ]  120
│           └── [http     http    ]  0f62a5622edcaf9f5da8c7b4870c74657279e144
└── [http     http    ]  web.config
```

**Comment by 2tata** [comment]
Does some one have an Idea? :)

**Comment by rafacamargo123** [comment]
selinux, maybe. selinux is like a firewall for files.
The quickest way to find out if that's the problem is to temporary disable it until next reboot:

run `setenforce 0` as root and try again.

If it works with the selinux off, there are many ways to solve it permanently. Then I suggest you to ask on the [forum](https://kanboard.discourse.group) because this is not an issue with kanboard itself, but with your environment.

**Comment by 2tata** [comment]
arch does not have SELinux active by default and I didn't activated it.

**Comment by igbanam** [comment]
I have a similar issue involving Heroku. I noticed my uploaded files weren't accessible after some time. I am currently using the file storage option for attached files.

Turns out when the dyno restarts, it may have wiped out (or removed access from) the previous data directory.

I also tried getting the AWS S3 Service as a storage point, but when the dynos restart, all plugins get cleared 🤷‍♂

**Comment by fguillot** [comment]
Please use the forum for installation issues.
