### ISSUE TITLE
Swimlane cannot be expanded once all others are removed

### ISSUE THREAD

**Issue by aslafy-z** [kanboard/kanboard#4376]
### Actual behaviour

Collapsed swimlane stays hidden even if there is only one that lefts (and toggles are hidden). 

### Expected behaviour

- Swimlane is not hidden if there is only one (even if has the collapsed state).
- Show swimlane toggle even if there is only one.

### Steps to reproduce

- Create a fresh project
- Add a task to the Default swimlane
- Create a Extra swimlane
- Collapse the Default swimlane
- Expand the Extra swimlane
- Delete the Extra swimlane
- Have a look to the Board
- Default swimlane disappeared

### Screenshots

Before deleting Extra swimlane

![2019-12-19 20_03_04-MySuperProject - Chromium](https://user-images.githubusercontent.com/8191198/71201796-13760b80-229b-11ea-9050-31dedfca5a69.png)

After deleting Extra swimlane

![2019-12-19 20_03_43-](https://user-images.githubusercontent.com/8191198/71201795-12dd7500-229b-11ea-9344-71c61d61905b.png)

### Configuration

- Kanboard version: I'm not admin on my instance, I was unable to find this information. Let me know if it's fixed now and I'll ask for an update at my side.
- OS: Windows 10 
- Browser: Chromium

Let me know if you need more details.
Thank you !

**Comment by psy-q** [comment]
Confirmed, we are seeing the same problem on Kanboard 1.2.14.

The problem is that Kanboard uses localstorage on the client side to save which swimlanes are supposed to be hidden. (it's in a hidden_swimlanes key in local storage, you can see it in your browser's storage inspector).

It stores e.g. `hidden_swimlanes_11 = [11,15] ` for a project with ID 11 where swimlanes with ID 11 and 15 are supposed to be hidden. But if there is only the default swimlane and this was e.g. ID 11, then the project will not show anything swimlanes at all to this client.

A proposed solution could be to store the hidden_swimlanes information server-side, query this every time a page is loaded and delete it all when a project with only one swimlane is rendered. The information serves no purpose in this case -- any newly created swimlanes will have different IDs anyhow.

Or then delete the information from the client's localstorage in the same way.
