### ISSUE TITLE
Deleting tasks when deleting a column (or swimlane) is dangerous - offer to reassign to another column / lane

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#439]
If you edit the board settings to delete a column, it warns you that it will delete all the tasks in that column.

Turns out this affects even closed tasks (that you may be unaware of).

This is dangerous. The safer/saner approach would be to have a prompt that says 'Reassign tasks from "column name" to another column: [ combobox here ]'

**Comment by levlaz** [comment]
I think it would be better if we marked items as `is_deleted` rather than actually removing them from the database. The reason why is: 

1. Storing text in a DB is cheap, losing some unrecoverable data is expensive 
2. In "Don't make me think" there is discussion on the UX pattern of letting the user do whatever they want and giving them a chance to recover, rather than continuously prompting them for anything that we deem "dangerous"  

This was especially true for me recently when I set up a new board and wanted to get rid of each column. Every time I hit delete column (even on an empty one) I was warned that I would lose all of my tasks (which did not exist). IMHO it would have been a better UX to just mark those columns, projects, tasks, subtasks, etc as `is_deleted` and not show them rather than prompting the user. 

Of course this would also require creating some sort of trash bin so that you could recover deleted items or even have the option of deleting them "for real".

**Comment by shimza** [comment]
I totally agree. The undo feature became standard ux practice about 20
years ago. No app actually deletes data anymore, it's appended, date
stamped new or marked non-current.

**Comment by eurodrew555** [comment]
I've also submitted a related feature request at https://github.com/kanboard/kanboard/issues/2943 to show the current number of open/closed tasks on the "edit columns" page. This would help in preventing deleting columns that contain tasks.

**Comment by fguillot** [comment]
In version 1.0.39, a very simple approach is used now, if a columns contains tasks, the menu entry to remove a column doesn't appear anymore. In addition, the number of open and closed tasks are shown in the table.

I know that this is not perfect, but at least that prevent people to lost data if they don't read the confirmation message.
