### ISSUE TITLE
plugin assets don't load from modified PLUGIN_DIR

### ISSUE THREAD

**Issue by ReedyBear** [kanboard/kanboard#4721]
Its likely that fixing this issue will remove the need for PR https://github.com/kanboard/kanboard/pull/4720

### Actual behaviour
When I change PLUGIN_DIR, the relpath given by plugins, like `template => plugins/Blueboard/skin.css`, does not point to an existing file any more & the assets do not load. Also, the filemtime fails.

### Expected behaviour
plugins will continue to work regardless what directory they're stored in

### Steps to reproduce
1. define('PLUGINS_DIR', $_SERVER['DOCUMENT_ROOT'].'/kanboard-plugins/') in `data/config.php`
2. Install a plugin, such as [blueboard](https://github.com/bgibout/blueboard) to `kanboard-plugins/Blueboard`
3. The theme from Blueboard does not apply.

If the above config is then removed & Blueboard is moved to `plugins/Blueboard`, the theme shows. Alternatively, Blueboard's src can be modified to point to `kanboard-plugins/Blueboard/skin.css`.

### Screenshots
None

### Logs
Not necessary

### Configuration

- Kanboard version: master branch commit 1aa1751f "Bump symfony/stopwatch from 5.2.1 to 5.2.2"
- Database type and version: sqlite, default
- PHP version: 7.4.14
- OS: Fedora 33
- Browser: Firefox, but surely not relevant

**Comment by Taeluf** [comment]
The solution I have in mind is somewhat sloppy.

`app/Helper/AssetHelper.php` has two functions `css()` and `js()`. These are called by `HookHelper->asset()`. 
`css()` and `js()` both receive `$filename` as first arg, which is something like `plugins/Blueboard/skin.css`

Since existing plugins rely upon `plugins/`, we would need to keep that functional.

Input into `css()` function:
`$filename = 'plugins/Blueboard/skin.css'`

call a helper function which will return;
`$filename = 'kanboard-plugins/Blueboard/skin.css`

This can be done by comparing `dirname(__DIR__,2)` to `PLUGINS_DIR` & finding the relative path from `dirname(__DIR__,2)` to `PLUGINS_DIR`.

I might submit a PR with this idea, but feedback on it would be nice. I'll need to work on it a little bit to figure out the path conversion thing.

**Comment by fguillot** [comment]
Closing issue. See https://github.com/kanboard/kanboard/pull/4723#issuecomment-1045210061
