### ISSUE TITLE
First swimlane title should be above the column names for UI consistency [Screenshot examples included]

### ISSUE THREAD

**Issue by groovybluedog** [kanboard/kanboard#4759]
When having a project with multiple swimlanes, on the first swimlane, the column names are above and then the swimelane name below. However for all other swimlanes, the swimlane name is above and the column name is below.

![image](https://user-images.githubusercontent.com/16142383/111856795-2277bd80-8925-11eb-89ac-3c8c81c104f4.png)

I find this UI choice a bit odd, and this seemingly minor difference is inconsistent and can be confusing to new users. 

I feel that, when there are multiple swimlanes, the first one should replicate the others and have the column name below, which should also hide when the swimlane name is collapsed. I do not feel that there is a need to have a "sticky" column name at the top when it always shows under all other swimlanes anyway.

This is my bad example in Paint of a more consistent UI when swimlanes are involved.

![image](https://user-images.githubusercontent.com/16142383/111856949-28ba6980-8926-11eb-8254-51bbf38d28f0.png)

- [ AFFIRMATIVE ] I have read this document: https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-are-you-not-developing-my-feature-request

**Comment by manne65-hd** [comment]
@groovybluedog 
I am also facing the issue, that my new users find this confusing ... however after my investigations, the column-header must be rendered first in order for the **collapse-column-feature** to work correctly.
So I decided to go with the seond-best attempt and make introduce a consistent behaviour _(column-header first / swimlane-header second)_ for all swimlanes.

Let's see if my Pull-request gets accepted ... otherwise I consider releasing this as a plugin.
