### ISSUE TITLE
plugin rocket.chat updating

### ISSUE THREAD

**Issue by Sicoval31** [kanboard/kanboard#4766]
Bonjour, le plugin pour Rocket.chat ne semble plus être maintenu (slack oui .... c'est moche).
Depuis la MAJ kanboard, les notifications ne fonctionnent plus !
Quel dommage, pourquoi ne plus maintenir ce plugin, RC est de plus en plus utilisé

**Comment by oliviermaridat** [comment]
Bonjour @Sicoval31 

Le maintenance du plugin rocketchat a été reprise : https://github.com/oliviermaridat/plugin-rocketchat
Il fonctionne avec la dernière version de KB.

Comme on peut le voir ici, le listing "officiel" des plugins pointent vers ce nouveau repository : https://github.com/kanboard/website/blob/master/plugins.html#L513

----

Hi @Sicoval31 

Updates of the rocketchat plugin are now provided there: https://github.com/oliviermaridat/plugin-rocketchat
It is working with the last version of KB.

This repository is now listed in the "official" list of plugins: https://github.com/kanboard/website/blob/master/plugins.html#L513

@fguillot Would you consider to update the README of https://github.com/kanboard/plugin-rocketchat to point to https://github.com/oliviermaridat/plugin-rocketchat please? Since this repository is archived, I cannot propose a PR anymore. Thanks a lot:

**Comment by fguillot** [comment]
Added link to fork https://github.com/kanboard/plugin-rocketchat:

![image](https://user-images.githubusercontent.com/323546/113243476-f125b880-9267-11eb-86dd-2af9e3c0770a.png)
