### ISSUE TITLE
Task limits aren't applied across swimlanes

### ISSUE THREAD

**Issue by dlocke** [kanboard/kanboard#861]
We would like to use swim lanes to differentiate which project a task is for and apply the task limit for a column across swim lanes.  Instead, we have found that the task limit is applied for each swim lane individually.

**Comment by cgudrian** [comment]
I was just about to create this feature request myself.

**Comment by shedatc** [comment]
+1
This feature would be very useful because swimlanes are, AFAIK, the only way to get a view of all the tasks without regard for there project.

**Comment by motobeats** [comment]
+1
Like the swimlanes for organizing workflows but still need a universal WIP limit.

**Comment by nicoespeon** [comment]
Hi there!

Currently trying [framaboard](https://framaboard.org/) which is an instance of Kanboard, this is precisely the point which drives me here. 

Swimlanes & WIP limits are perfect, but swimlanes would be far more usable if WIP were calculated through lanes in our case: the board represent the capacity of production of the team, which could work on different projects (= swimlanes) or have an "expedite" lane which should be considered into the WIP limit of columns instead of being unrelated — we'd rather create another board in that case.

Thanks a lot for this awesome tool, super useful :+1:

**Comment by mrfyx** [comment]
+1 need a universal WIP limit by column

**Comment by TheCloud** [comment]
+1 too on this, I think that after seeing so many +1 it should be pulled :-)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
