### ISSUE TITLE
Restrict user per subtask

### ISSUE THREAD

**Issue by Sorasma** [kanboard/kanboard#992]
wooow, seems that all users, and I mean reglar users, no project managers/admins, can see all tasks and subtasks in a project. This is really dangerous for the project because anyone can see the workflow and edit the project, even if I assign a user only at a subtask level he can still see workflow and all project tasks/subtasks and seems he can also edit them.

It should me normal to restrict users to see/edit on a subtask level. This is a huge security mistake. We work with external members that we sometimes meat for the first time and work with them only for one subtask . It's not normal to give them access to all the project.

Is it possible somehow to allow a user to see only tasks or subtasks he is assigned
Thanks

**Comment by froschdesign** [comment]
> This is a huge security mistake. We work with external members that we sometimes meat for the first time and work with them only for one subtask .

This is *your* use case, but for a traditional kanban board it doesn't matter.

**Comment by Sorasma** [comment]
@froschdesign I think that this is your case, because if you did had lots of project and also worked with a team outside your control ( a simple example can a translator, a person that translates a script) you should know it's advised to show team members only the subtasks and tasks they need to complete, and not all tasks in a project.  Not intending to offend you, but you see this only from your needs and perspective. A project management program needs to be a little bit more flexible.

Motive for my request is very simple:
1. Efficiency, project members can see and focus only on what they need to do, not what other needs to do.
2. Avoid confusion, I think it's self explaining.
3. Security of project data.
And of course there are lots of other reasons, that can be punctual/project based reason. For example protecting some data about expenses and costs or other project based private data, that you need to discuss only with project managers. Sure, we can make new project for that only with project managers, but it's stupid to open a new project that is about another project.

Just my 2 cents here.

**Comment by Alexvander** [comment]
:+1:  I see myself in the situation to create a new project with private information I want to hide, about a specific project. If I outsource some tasks I also create a new project for the same project and just name them "ProjectName#1.0" "ProjectName#1.1" "ProjectName#1.2" ...... aso and give access to users. Max I have are "ProjectName#1.5" for the same project.

I don't think this is a hard to implement feature. I'm happy to send some additional donation for this project only for this feature. Makes organization better, much better.

**Comment by froschdesign** [comment]
@Sorasma 
> I think that this is your case…

This is not the question.

@Alexvander
> I don't think this is a hard to implement feature.

This also not the question.

@Sorasma and @Alexvander
Don't get me wrong, I can see your use case. But remember the name and the goal of this software.

Here are two mission Statements:
 
>- Kanban methodology
- Minimalist software, focus only on essential features (Less is more)

(http://kanboard.net)

My proposal for a solution: a plugin system.

**Comment by Sorasma** [comment]
@froschdesign sure, a plugin system sound very good idea. Can you build my above request? Can we talk about costs, etc?

Thanks

**Comment by sparkles645** [comment]
@Sorasma 
How about this as a solution: 
* Create two projects in KB. 
* One internal board, for users you trust, and one external board - where you allow users for people you don't trust / don't wish to see everything.
* Don't use "Allow all users" on any of the projects - select those users who should have access one-by-one for all projects. 
* Don't activate public access on any of the projects.
**That way, you stay in control of what information is available to whom.**
* If information security is still an issue, run the internal boards on a dedicated local webserver with no external access.

* KB has good documentation - reading up on the docs and testing it out in terms of features and capabilities before implementing and going "live" is a natual thing to do, so the original post seems a bit odd.

**Comment by Sorasma** [comment]
@sparkles645 thanks for the suggestion, it's a good option on a short run, but on the long rune where you or me or anyone will start to have more and more projects this is just a shortcut that doesn't solve the problem. As I said, I'm offering to pay the requested cost to build this feature inside kanboard so everybody can benefit from it. 

Please let me know anyone here who can get it done. Thanks

**Comment by Sorasma** [comment]
@fguillot any news on this request? I stopped using Kandoard because of this issue 

Thanks

**Comment by froschdesign** [comment]
@Sorasma 
Please have a look at #1234.

**Comment by Sorasma** [comment]
Thanks @froschdesign I appreciate that :)

**Comment by 8bit-hero** [comment]
This issue quite limiting. it's inclusion would allow a variety of use case scenarios to be possible.

**Comment by fguillot** [comment]
Unfortunately, the number of features is voluntary limited otherwise the software will become too bloated. I cannot make a software that fit with the needs of everyone around the world.

If someone still interested by that, there is a custom role feature now and this system could be extended. Do not forget that Kanboard is a free and open source software.

**Comment by freeblue** [comment]
Hello, we are using kanboard since a week now and really like this application (IT department). I am working in a town hall and my intention (dream?) using this tool is to bring (step by step) the kanban and project management culture. Using this tool i would like to make aware my colleague (non IT department) of their own responsabilities and limit the work. We would like our non-IT colleagues or external providers to be able to see the whole board and status of a project and tasks assigned to them (this actually work) but something that is missing for us is a new role that prevent task modification/update/move between columns from a user whose task is not assigned. Because of my poor english i don't know if my description is clear enough....
We spend lot of time to fill the bords and unfortunately (because of the situation i described) we cannot actually permit our colleague to move/update task that are not assigned to them, it would be nice if they can see everything (+ notifications) but only interact with task assigned to them.
We are mainly managing IT projects but some non IT department have a role in these projects. There are also some external providers. As i said, a new role as described above would be really useful for us.
Because of this, we cannot open Kanboard to other users.
I understand kanboard is a free and open source software that's why my request is not a request but just a description of what we think to be a limiting feature (in our organisation of course).

Regards,

Alexandre 
Mairie de Sallanches

**Comment by aljawaid** [comment]
I have been using Kanboard for almost a year now, projects for my business have started creating the need for external non-staff to get involved.  Sadly, even as a user, they can see all my projects.  Some of the projects are personal to a few people only so private projects won't work. 

Ideal solution:  Allow option for only assigned users to have access to each board/task

**Comment by dhornford** [comment]
Already there
Look at Permissions for a Project & Users/Groups as an admin

-- 
Dave Hornford
Conexiam. Straightforward answers to complex problems.
www.conexiam.com | +1.403.818.4303

On February 25, 2017 at 6:01:46 PM, IJ (notifications@github.com) wrote:

I have been using Kanboard for almost a year now, projects for my business
have started creating the need for external non-staff to get involved.
Sadly, even as a user, they can see all my projects. Some of the projects
are personal to a few people only so private projects won't work.

Ideal solution: Allow option for only assigned users to have access to each
board/task

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanboard/kanboard/issues/992#issuecomment-282518952>,
or mute the thread

**Comment by aljawaid** [comment]
@dhornford Thank you for pointing me in the right direction... I have no idea how I missed that!

**Comment by Sorasma** [comment]
@dhornford @aljawaid @fguillot the Permissions for a Project & Users/Groups as an admin is a great improvement and I really appreciate it, but we are 1 single step behind, and that's a way to allow tasks to be view only by specific members. In actual situation we can only limit users per project, but we can't limit them to view, open tasks that are not for them. If we have to work only with 1 single department per each project the above solution is ok, but in situations when multiple departments work on a client project (it, design, marketing, external assistants, etc..) and also offer option to client to view status of his project we can't make only one project per client because we will mix them together, and just moving one task from a column to another by accident will make problems. Not to mention that external assistants will have access to all tasks.....

A simple implementation can solve all the above problems:
